// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_user_itg_server.proto

#include "app_user_itg_server.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace trpc {
namespace app {
constexpr AppUserInfo::AppUserInfo(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : appid_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , phone_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , user_name_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , register_time_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , password_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , icon_url_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct AppUserInfoDefaultTypeInternal {
  constexpr AppUserInfoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~AppUserInfoDefaultTypeInternal() {}
  union {
    AppUserInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT AppUserInfoDefaultTypeInternal _AppUserInfo_default_instance_;
constexpr AppUserRegisterReq::AppUserRegisterReq(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : public_key_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , user_info_(nullptr){}
struct AppUserRegisterReqDefaultTypeInternal {
  constexpr AppUserRegisterReqDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~AppUserRegisterReqDefaultTypeInternal() {}
  union {
    AppUserRegisterReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT AppUserRegisterReqDefaultTypeInternal _AppUserRegisterReq_default_instance_;
constexpr AppUserRegisterRsp::AppUserRegisterRsp(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : appid_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , uid_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct AppUserRegisterRspDefaultTypeInternal {
  constexpr AppUserRegisterRspDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~AppUserRegisterRspDefaultTypeInternal() {}
  union {
    AppUserRegisterRsp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT AppUserRegisterRspDefaultTypeInternal _AppUserRegisterRsp_default_instance_;
constexpr AppUserQueryInfoReq::AppUserQueryInfoReq(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : condition_type_(0u)
  , _oneof_case_{}{}
struct AppUserQueryInfoReqDefaultTypeInternal {
  constexpr AppUserQueryInfoReqDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~AppUserQueryInfoReqDefaultTypeInternal() {}
  union {
    AppUserQueryInfoReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT AppUserQueryInfoReqDefaultTypeInternal _AppUserQueryInfoReq_default_instance_;
constexpr AppUserQueryInfoRsp::AppUserQueryInfoRsp(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : user_info_(nullptr){}
struct AppUserQueryInfoRspDefaultTypeInternal {
  constexpr AppUserQueryInfoRspDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~AppUserQueryInfoRspDefaultTypeInternal() {}
  union {
    AppUserQueryInfoRsp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT AppUserQueryInfoRspDefaultTypeInternal _AppUserQueryInfoRsp_default_instance_;
}  // namespace app
}  // namespace trpc
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_app_5fuser_5fitg_5fserver_2eproto[5];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_app_5fuser_5fitg_5fserver_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_app_5fuser_5fitg_5fserver_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_app_5fuser_5fitg_5fserver_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserInfo, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserInfo, appid_),
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserInfo, phone_),
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserInfo, user_name_),
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserInfo, register_time_),
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserInfo, password_),
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserInfo, icon_url_),
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserRegisterReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserRegisterReq, user_info_),
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserRegisterReq, public_key_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserRegisterRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserRegisterRsp, appid_),
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserRegisterRsp, uid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserQueryInfoReq, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserQueryInfoReq, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserQueryInfoReq, condition_type_),
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserQueryInfoReq, condition_value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserQueryInfoRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::trpc::app::AppUserQueryInfoRsp, user_info_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 11, sizeof(::trpc::app::AppUserInfo)},
  { 17, -1, sizeof(::trpc::app::AppUserRegisterReq)},
  { 24, -1, sizeof(::trpc::app::AppUserRegisterRsp)},
  { 31, -1, sizeof(::trpc::app::AppUserQueryInfoReq)},
  { 40, -1, sizeof(::trpc::app::AppUserQueryInfoRsp)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::trpc::app::_AppUserInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::trpc::app::_AppUserRegisterReq_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::trpc::app::_AppUserRegisterRsp_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::trpc::app::_AppUserQueryInfoReq_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::trpc::app::_AppUserQueryInfoRsp_default_instance_),
};

const char descriptor_table_protodef_app_5fuser_5fitg_5fserver_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031app_user_itg_server.proto\022\010trpc.app\"\235\001"
  "\n\013AppUserInfo\022\r\n\005appid\030\001 \001(\t\022\r\n\005phone\030\002 "
  "\001(\t\022\021\n\tuser_name\030\003 \001(\t\022\025\n\rregister_time\030"
  "\004 \001(\t\022\025\n\010password\030\005 \001(\tH\000\210\001\001\022\025\n\010icon_url"
  "\030\006 \001(\tH\001\210\001\001B\013\n\t_passwordB\013\n\t_icon_url\"R\n"
  "\022AppUserRegisterReq\022(\n\tuser_info\030\001 \001(\0132\025"
  ".trpc.app.AppUserInfo\022\022\n\npublic_key\030\002 \001("
  "\t\"0\n\022AppUserRegisterRsp\022\r\n\005appid\030\001 \001(\t\022\013"
  "\n\003uid\030\002 \001(\t\"`\n\023AppUserQueryInfoReq\022\026\n\016co"
  "ndition_type\030\001 \001(\r\022\r\n\003uid\030\002 \001(\tH\000\022\017\n\005pho"
  "ne\030\003 \001(\tH\000B\021\n\017condition_value\"\?\n\023AppUser"
  "QueryInfoRsp\022(\n\tuser_info\030\001 \001(\0132\025.trpc.a"
  "pp.AppUserInfo2\306\001\n\021AppUserItgService\022V\n\026"
  "AppUserRegisterHandler\022\034.trpc.app.AppUse"
  "rRegisterReq\032\034.trpc.app.AppUserRegisterR"
  "sp\"\000\022Y\n\027AppUserQueryInfoHandler\022\035.trpc.a"
  "pp.AppUserQueryInfoReq\032\035.trpc.app.AppUse"
  "rQueryInfoRsp\"\000b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_app_5fuser_5fitg_5fserver_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_app_5fuser_5fitg_5fserver_2eproto = {
  false, false, 703, descriptor_table_protodef_app_5fuser_5fitg_5fserver_2eproto, "app_user_itg_server.proto", 
  &descriptor_table_app_5fuser_5fitg_5fserver_2eproto_once, nullptr, 0, 5,
  schemas, file_default_instances, TableStruct_app_5fuser_5fitg_5fserver_2eproto::offsets,
  file_level_metadata_app_5fuser_5fitg_5fserver_2eproto, file_level_enum_descriptors_app_5fuser_5fitg_5fserver_2eproto, file_level_service_descriptors_app_5fuser_5fitg_5fserver_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_app_5fuser_5fitg_5fserver_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_app_5fuser_5fitg_5fserver_2eproto);
  return descriptor_table_app_5fuser_5fitg_5fserver_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_app_5fuser_5fitg_5fserver_2eproto(&descriptor_table_app_5fuser_5fitg_5fserver_2eproto);
namespace trpc {
namespace app {

// ===================================================================

class AppUserInfo::_Internal {
 public:
  using HasBits = decltype(std::declval<AppUserInfo>()._has_bits_);
  static void set_has_password(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_icon_url(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

AppUserInfo::AppUserInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:trpc.app.AppUserInfo)
}
AppUserInfo::AppUserInfo(const AppUserInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  appid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_appid().empty()) {
    appid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_appid(), 
      GetArena());
  }
  phone_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_phone().empty()) {
    phone_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_phone(), 
      GetArena());
  }
  user_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_user_name().empty()) {
    user_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_user_name(), 
      GetArena());
  }
  register_time_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_register_time().empty()) {
    register_time_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_register_time(), 
      GetArena());
  }
  password_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_password()) {
    password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_password(), 
      GetArena());
  }
  icon_url_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_icon_url()) {
    icon_url_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_icon_url(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:trpc.app.AppUserInfo)
}

void AppUserInfo::SharedCtor() {
appid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
phone_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
user_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
register_time_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
password_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
icon_url_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

AppUserInfo::~AppUserInfo() {
  // @@protoc_insertion_point(destructor:trpc.app.AppUserInfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void AppUserInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  appid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  phone_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  user_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  register_time_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  icon_url_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void AppUserInfo::ArenaDtor(void* object) {
  AppUserInfo* _this = reinterpret_cast< AppUserInfo* >(object);
  (void)_this;
}
void AppUserInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void AppUserInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void AppUserInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:trpc.app.AppUserInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  appid_.ClearToEmpty();
  phone_.ClearToEmpty();
  user_name_.ClearToEmpty();
  register_time_.ClearToEmpty();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      password_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      icon_url_.ClearNonDefaultToEmpty();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AppUserInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string appid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_appid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "trpc.app.AppUserInfo.appid"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string phone = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_phone();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "trpc.app.AppUserInfo.phone"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string user_name = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_user_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "trpc.app.AppUserInfo.user_name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string register_time = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_register_time();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "trpc.app.AppUserInfo.register_time"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string password = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_password();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "trpc.app.AppUserInfo.password"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string icon_url = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_icon_url();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "trpc.app.AppUserInfo.icon_url"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AppUserInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:trpc.app.AppUserInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string appid = 1;
  if (this->appid().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_appid().data(), static_cast<int>(this->_internal_appid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "trpc.app.AppUserInfo.appid");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_appid(), target);
  }

  // string phone = 2;
  if (this->phone().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_phone().data(), static_cast<int>(this->_internal_phone().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "trpc.app.AppUserInfo.phone");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_phone(), target);
  }

  // string user_name = 3;
  if (this->user_name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_user_name().data(), static_cast<int>(this->_internal_user_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "trpc.app.AppUserInfo.user_name");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_user_name(), target);
  }

  // string register_time = 4;
  if (this->register_time().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_register_time().data(), static_cast<int>(this->_internal_register_time().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "trpc.app.AppUserInfo.register_time");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_register_time(), target);
  }

  // string password = 5;
  if (_internal_has_password()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_password().data(), static_cast<int>(this->_internal_password().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "trpc.app.AppUserInfo.password");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_password(), target);
  }

  // string icon_url = 6;
  if (_internal_has_icon_url()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_icon_url().data(), static_cast<int>(this->_internal_icon_url().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "trpc.app.AppUserInfo.icon_url");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_icon_url(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:trpc.app.AppUserInfo)
  return target;
}

size_t AppUserInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:trpc.app.AppUserInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string appid = 1;
  if (this->appid().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_appid());
  }

  // string phone = 2;
  if (this->phone().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_phone());
  }

  // string user_name = 3;
  if (this->user_name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_user_name());
  }

  // string register_time = 4;
  if (this->register_time().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_register_time());
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // string password = 5;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_password());
    }

    // string icon_url = 6;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_icon_url());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AppUserInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:trpc.app.AppUserInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const AppUserInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AppUserInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:trpc.app.AppUserInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:trpc.app.AppUserInfo)
    MergeFrom(*source);
  }
}

void AppUserInfo::MergeFrom(const AppUserInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:trpc.app.AppUserInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.appid().size() > 0) {
    _internal_set_appid(from._internal_appid());
  }
  if (from.phone().size() > 0) {
    _internal_set_phone(from._internal_phone());
  }
  if (from.user_name().size() > 0) {
    _internal_set_user_name(from._internal_user_name());
  }
  if (from.register_time().size() > 0) {
    _internal_set_register_time(from._internal_register_time());
  }
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_password(from._internal_password());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_icon_url(from._internal_icon_url());
    }
  }
}

void AppUserInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:trpc.app.AppUserInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AppUserInfo::CopyFrom(const AppUserInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:trpc.app.AppUserInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AppUserInfo::IsInitialized() const {
  return true;
}

void AppUserInfo::InternalSwap(AppUserInfo* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  appid_.Swap(&other->appid_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  phone_.Swap(&other->phone_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  user_name_.Swap(&other->user_name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  register_time_.Swap(&other->register_time_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  password_.Swap(&other->password_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  icon_url_.Swap(&other->icon_url_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata AppUserInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class AppUserRegisterReq::_Internal {
 public:
  static const ::trpc::app::AppUserInfo& user_info(const AppUserRegisterReq* msg);
};

const ::trpc::app::AppUserInfo&
AppUserRegisterReq::_Internal::user_info(const AppUserRegisterReq* msg) {
  return *msg->user_info_;
}
AppUserRegisterReq::AppUserRegisterReq(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:trpc.app.AppUserRegisterReq)
}
AppUserRegisterReq::AppUserRegisterReq(const AppUserRegisterReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  public_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_public_key().empty()) {
    public_key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_public_key(), 
      GetArena());
  }
  if (from._internal_has_user_info()) {
    user_info_ = new ::trpc::app::AppUserInfo(*from.user_info_);
  } else {
    user_info_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:trpc.app.AppUserRegisterReq)
}

void AppUserRegisterReq::SharedCtor() {
public_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
user_info_ = nullptr;
}

AppUserRegisterReq::~AppUserRegisterReq() {
  // @@protoc_insertion_point(destructor:trpc.app.AppUserRegisterReq)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void AppUserRegisterReq::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  public_key_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete user_info_;
}

void AppUserRegisterReq::ArenaDtor(void* object) {
  AppUserRegisterReq* _this = reinterpret_cast< AppUserRegisterReq* >(object);
  (void)_this;
}
void AppUserRegisterReq::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void AppUserRegisterReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void AppUserRegisterReq::Clear() {
// @@protoc_insertion_point(message_clear_start:trpc.app.AppUserRegisterReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  public_key_.ClearToEmpty();
  if (GetArena() == nullptr && user_info_ != nullptr) {
    delete user_info_;
  }
  user_info_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AppUserRegisterReq::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .trpc.app.AppUserInfo user_info = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_user_info(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string public_key = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_public_key();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "trpc.app.AppUserRegisterReq.public_key"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AppUserRegisterReq::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:trpc.app.AppUserRegisterReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .trpc.app.AppUserInfo user_info = 1;
  if (this->has_user_info()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::user_info(this), target, stream);
  }

  // string public_key = 2;
  if (this->public_key().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_public_key().data(), static_cast<int>(this->_internal_public_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "trpc.app.AppUserRegisterReq.public_key");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_public_key(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:trpc.app.AppUserRegisterReq)
  return target;
}

size_t AppUserRegisterReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:trpc.app.AppUserRegisterReq)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string public_key = 2;
  if (this->public_key().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_public_key());
  }

  // .trpc.app.AppUserInfo user_info = 1;
  if (this->has_user_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *user_info_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AppUserRegisterReq::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:trpc.app.AppUserRegisterReq)
  GOOGLE_DCHECK_NE(&from, this);
  const AppUserRegisterReq* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AppUserRegisterReq>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:trpc.app.AppUserRegisterReq)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:trpc.app.AppUserRegisterReq)
    MergeFrom(*source);
  }
}

void AppUserRegisterReq::MergeFrom(const AppUserRegisterReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:trpc.app.AppUserRegisterReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.public_key().size() > 0) {
    _internal_set_public_key(from._internal_public_key());
  }
  if (from.has_user_info()) {
    _internal_mutable_user_info()->::trpc::app::AppUserInfo::MergeFrom(from._internal_user_info());
  }
}

void AppUserRegisterReq::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:trpc.app.AppUserRegisterReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AppUserRegisterReq::CopyFrom(const AppUserRegisterReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:trpc.app.AppUserRegisterReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AppUserRegisterReq::IsInitialized() const {
  return true;
}

void AppUserRegisterReq::InternalSwap(AppUserRegisterReq* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  public_key_.Swap(&other->public_key_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(user_info_, other->user_info_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AppUserRegisterReq::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class AppUserRegisterRsp::_Internal {
 public:
};

AppUserRegisterRsp::AppUserRegisterRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:trpc.app.AppUserRegisterRsp)
}
AppUserRegisterRsp::AppUserRegisterRsp(const AppUserRegisterRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  appid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_appid().empty()) {
    appid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_appid(), 
      GetArena());
  }
  uid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_uid().empty()) {
    uid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_uid(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:trpc.app.AppUserRegisterRsp)
}

void AppUserRegisterRsp::SharedCtor() {
appid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
uid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

AppUserRegisterRsp::~AppUserRegisterRsp() {
  // @@protoc_insertion_point(destructor:trpc.app.AppUserRegisterRsp)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void AppUserRegisterRsp::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  appid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  uid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void AppUserRegisterRsp::ArenaDtor(void* object) {
  AppUserRegisterRsp* _this = reinterpret_cast< AppUserRegisterRsp* >(object);
  (void)_this;
}
void AppUserRegisterRsp::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void AppUserRegisterRsp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void AppUserRegisterRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:trpc.app.AppUserRegisterRsp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  appid_.ClearToEmpty();
  uid_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AppUserRegisterRsp::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string appid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_appid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "trpc.app.AppUserRegisterRsp.appid"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string uid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_uid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "trpc.app.AppUserRegisterRsp.uid"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AppUserRegisterRsp::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:trpc.app.AppUserRegisterRsp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string appid = 1;
  if (this->appid().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_appid().data(), static_cast<int>(this->_internal_appid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "trpc.app.AppUserRegisterRsp.appid");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_appid(), target);
  }

  // string uid = 2;
  if (this->uid().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_uid().data(), static_cast<int>(this->_internal_uid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "trpc.app.AppUserRegisterRsp.uid");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_uid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:trpc.app.AppUserRegisterRsp)
  return target;
}

size_t AppUserRegisterRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:trpc.app.AppUserRegisterRsp)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string appid = 1;
  if (this->appid().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_appid());
  }

  // string uid = 2;
  if (this->uid().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_uid());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AppUserRegisterRsp::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:trpc.app.AppUserRegisterRsp)
  GOOGLE_DCHECK_NE(&from, this);
  const AppUserRegisterRsp* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AppUserRegisterRsp>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:trpc.app.AppUserRegisterRsp)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:trpc.app.AppUserRegisterRsp)
    MergeFrom(*source);
  }
}

void AppUserRegisterRsp::MergeFrom(const AppUserRegisterRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:trpc.app.AppUserRegisterRsp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.appid().size() > 0) {
    _internal_set_appid(from._internal_appid());
  }
  if (from.uid().size() > 0) {
    _internal_set_uid(from._internal_uid());
  }
}

void AppUserRegisterRsp::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:trpc.app.AppUserRegisterRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AppUserRegisterRsp::CopyFrom(const AppUserRegisterRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:trpc.app.AppUserRegisterRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AppUserRegisterRsp::IsInitialized() const {
  return true;
}

void AppUserRegisterRsp::InternalSwap(AppUserRegisterRsp* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  appid_.Swap(&other->appid_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  uid_.Swap(&other->uid_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata AppUserRegisterRsp::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class AppUserQueryInfoReq::_Internal {
 public:
};

AppUserQueryInfoReq::AppUserQueryInfoReq(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:trpc.app.AppUserQueryInfoReq)
}
AppUserQueryInfoReq::AppUserQueryInfoReq(const AppUserQueryInfoReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  condition_type_ = from.condition_type_;
  clear_has_condition_value();
  switch (from.condition_value_case()) {
    case kUid: {
      _internal_set_uid(from._internal_uid());
      break;
    }
    case kPhone: {
      _internal_set_phone(from._internal_phone());
      break;
    }
    case CONDITION_VALUE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:trpc.app.AppUserQueryInfoReq)
}

void AppUserQueryInfoReq::SharedCtor() {
condition_type_ = 0u;
clear_has_condition_value();
}

AppUserQueryInfoReq::~AppUserQueryInfoReq() {
  // @@protoc_insertion_point(destructor:trpc.app.AppUserQueryInfoReq)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void AppUserQueryInfoReq::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (has_condition_value()) {
    clear_condition_value();
  }
}

void AppUserQueryInfoReq::ArenaDtor(void* object) {
  AppUserQueryInfoReq* _this = reinterpret_cast< AppUserQueryInfoReq* >(object);
  (void)_this;
}
void AppUserQueryInfoReq::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void AppUserQueryInfoReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void AppUserQueryInfoReq::clear_condition_value() {
// @@protoc_insertion_point(one_of_clear_start:trpc.app.AppUserQueryInfoReq)
  switch (condition_value_case()) {
    case kUid: {
      condition_value_.uid_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
      break;
    }
    case kPhone: {
      condition_value_.phone_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
      break;
    }
    case CONDITION_VALUE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = CONDITION_VALUE_NOT_SET;
}


void AppUserQueryInfoReq::Clear() {
// @@protoc_insertion_point(message_clear_start:trpc.app.AppUserQueryInfoReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  condition_type_ = 0u;
  clear_condition_value();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AppUserQueryInfoReq::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 condition_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          condition_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string uid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_uid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "trpc.app.AppUserQueryInfoReq.uid"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string phone = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_phone();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "trpc.app.AppUserQueryInfoReq.phone"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AppUserQueryInfoReq::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:trpc.app.AppUserQueryInfoReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 condition_type = 1;
  if (this->condition_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_condition_type(), target);
  }

  // string uid = 2;
  if (_internal_has_uid()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_uid().data(), static_cast<int>(this->_internal_uid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "trpc.app.AppUserQueryInfoReq.uid");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_uid(), target);
  }

  // string phone = 3;
  if (_internal_has_phone()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_phone().data(), static_cast<int>(this->_internal_phone().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "trpc.app.AppUserQueryInfoReq.phone");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_phone(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:trpc.app.AppUserQueryInfoReq)
  return target;
}

size_t AppUserQueryInfoReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:trpc.app.AppUserQueryInfoReq)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 condition_type = 1;
  if (this->condition_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_condition_type());
  }

  switch (condition_value_case()) {
    // string uid = 2;
    case kUid: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_uid());
      break;
    }
    // string phone = 3;
    case kPhone: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_phone());
      break;
    }
    case CONDITION_VALUE_NOT_SET: {
      break;
    }
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AppUserQueryInfoReq::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:trpc.app.AppUserQueryInfoReq)
  GOOGLE_DCHECK_NE(&from, this);
  const AppUserQueryInfoReq* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AppUserQueryInfoReq>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:trpc.app.AppUserQueryInfoReq)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:trpc.app.AppUserQueryInfoReq)
    MergeFrom(*source);
  }
}

void AppUserQueryInfoReq::MergeFrom(const AppUserQueryInfoReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:trpc.app.AppUserQueryInfoReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.condition_type() != 0) {
    _internal_set_condition_type(from._internal_condition_type());
  }
  switch (from.condition_value_case()) {
    case kUid: {
      _internal_set_uid(from._internal_uid());
      break;
    }
    case kPhone: {
      _internal_set_phone(from._internal_phone());
      break;
    }
    case CONDITION_VALUE_NOT_SET: {
      break;
    }
  }
}

void AppUserQueryInfoReq::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:trpc.app.AppUserQueryInfoReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AppUserQueryInfoReq::CopyFrom(const AppUserQueryInfoReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:trpc.app.AppUserQueryInfoReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AppUserQueryInfoReq::IsInitialized() const {
  return true;
}

void AppUserQueryInfoReq::InternalSwap(AppUserQueryInfoReq* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(condition_type_, other->condition_type_);
  swap(condition_value_, other->condition_value_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata AppUserQueryInfoReq::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class AppUserQueryInfoRsp::_Internal {
 public:
  static const ::trpc::app::AppUserInfo& user_info(const AppUserQueryInfoRsp* msg);
};

const ::trpc::app::AppUserInfo&
AppUserQueryInfoRsp::_Internal::user_info(const AppUserQueryInfoRsp* msg) {
  return *msg->user_info_;
}
AppUserQueryInfoRsp::AppUserQueryInfoRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:trpc.app.AppUserQueryInfoRsp)
}
AppUserQueryInfoRsp::AppUserQueryInfoRsp(const AppUserQueryInfoRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_user_info()) {
    user_info_ = new ::trpc::app::AppUserInfo(*from.user_info_);
  } else {
    user_info_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:trpc.app.AppUserQueryInfoRsp)
}

void AppUserQueryInfoRsp::SharedCtor() {
user_info_ = nullptr;
}

AppUserQueryInfoRsp::~AppUserQueryInfoRsp() {
  // @@protoc_insertion_point(destructor:trpc.app.AppUserQueryInfoRsp)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void AppUserQueryInfoRsp::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete user_info_;
}

void AppUserQueryInfoRsp::ArenaDtor(void* object) {
  AppUserQueryInfoRsp* _this = reinterpret_cast< AppUserQueryInfoRsp* >(object);
  (void)_this;
}
void AppUserQueryInfoRsp::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void AppUserQueryInfoRsp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void AppUserQueryInfoRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:trpc.app.AppUserQueryInfoRsp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && user_info_ != nullptr) {
    delete user_info_;
  }
  user_info_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AppUserQueryInfoRsp::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .trpc.app.AppUserInfo user_info = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_user_info(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AppUserQueryInfoRsp::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:trpc.app.AppUserQueryInfoRsp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .trpc.app.AppUserInfo user_info = 1;
  if (this->has_user_info()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::user_info(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:trpc.app.AppUserQueryInfoRsp)
  return target;
}

size_t AppUserQueryInfoRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:trpc.app.AppUserQueryInfoRsp)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .trpc.app.AppUserInfo user_info = 1;
  if (this->has_user_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *user_info_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AppUserQueryInfoRsp::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:trpc.app.AppUserQueryInfoRsp)
  GOOGLE_DCHECK_NE(&from, this);
  const AppUserQueryInfoRsp* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AppUserQueryInfoRsp>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:trpc.app.AppUserQueryInfoRsp)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:trpc.app.AppUserQueryInfoRsp)
    MergeFrom(*source);
  }
}

void AppUserQueryInfoRsp::MergeFrom(const AppUserQueryInfoRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:trpc.app.AppUserQueryInfoRsp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_user_info()) {
    _internal_mutable_user_info()->::trpc::app::AppUserInfo::MergeFrom(from._internal_user_info());
  }
}

void AppUserQueryInfoRsp::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:trpc.app.AppUserQueryInfoRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AppUserQueryInfoRsp::CopyFrom(const AppUserQueryInfoRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:trpc.app.AppUserQueryInfoRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AppUserQueryInfoRsp::IsInitialized() const {
  return true;
}

void AppUserQueryInfoRsp::InternalSwap(AppUserQueryInfoRsp* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(user_info_, other->user_info_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AppUserQueryInfoRsp::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace app
}  // namespace trpc
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::trpc::app::AppUserInfo* Arena::CreateMaybeMessage< ::trpc::app::AppUserInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::trpc::app::AppUserInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::trpc::app::AppUserRegisterReq* Arena::CreateMaybeMessage< ::trpc::app::AppUserRegisterReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::trpc::app::AppUserRegisterReq >(arena);
}
template<> PROTOBUF_NOINLINE ::trpc::app::AppUserRegisterRsp* Arena::CreateMaybeMessage< ::trpc::app::AppUserRegisterRsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::trpc::app::AppUserRegisterRsp >(arena);
}
template<> PROTOBUF_NOINLINE ::trpc::app::AppUserQueryInfoReq* Arena::CreateMaybeMessage< ::trpc::app::AppUserQueryInfoReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::trpc::app::AppUserQueryInfoReq >(arena);
}
template<> PROTOBUF_NOINLINE ::trpc::app::AppUserQueryInfoRsp* Arena::CreateMaybeMessage< ::trpc::app::AppUserQueryInfoRsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::trpc::app::AppUserQueryInfoRsp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
