// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_busi_itg_server.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_app_5fbusi_5fitg_5fserver_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_app_5fbusi_5fitg_5fserver_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_app_5fbusi_5fitg_5fserver_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_app_5fbusi_5fitg_5fserver_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_app_5fbusi_5fitg_5fserver_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_app_5fbusi_5fitg_5fserver_2eproto_metadata_getter(int index);
namespace trpc {
namespace app {
class AppBusiBaseAuguryReq;
struct AppBusiBaseAuguryReqDefaultTypeInternal;
extern AppBusiBaseAuguryReqDefaultTypeInternal _AppBusiBaseAuguryReq_default_instance_;
class AppBusiBaseAuguryRsp;
struct AppBusiBaseAuguryRspDefaultTypeInternal;
extern AppBusiBaseAuguryRspDefaultTypeInternal _AppBusiBaseAuguryRsp_default_instance_;
class AppBusiBirthdateConvertReq;
struct AppBusiBirthdateConvertReqDefaultTypeInternal;
extern AppBusiBirthdateConvertReqDefaultTypeInternal _AppBusiBirthdateConvertReq_default_instance_;
class AppBusiBirthdateConvertRsp;
struct AppBusiBirthdateConvertRspDefaultTypeInternal;
extern AppBusiBirthdateConvertRspDefaultTypeInternal _AppBusiBirthdateConvertRsp_default_instance_;
}  // namespace app
}  // namespace trpc
PROTOBUF_NAMESPACE_OPEN
template<> ::trpc::app::AppBusiBaseAuguryReq* Arena::CreateMaybeMessage<::trpc::app::AppBusiBaseAuguryReq>(Arena*);
template<> ::trpc::app::AppBusiBaseAuguryRsp* Arena::CreateMaybeMessage<::trpc::app::AppBusiBaseAuguryRsp>(Arena*);
template<> ::trpc::app::AppBusiBirthdateConvertReq* Arena::CreateMaybeMessage<::trpc::app::AppBusiBirthdateConvertReq>(Arena*);
template<> ::trpc::app::AppBusiBirthdateConvertRsp* Arena::CreateMaybeMessage<::trpc::app::AppBusiBirthdateConvertRsp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace trpc {
namespace app {

// ===================================================================

class AppBusiBirthdateConvertReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:trpc.app.AppBusiBirthdateConvertReq) */ {
 public:
  inline AppBusiBirthdateConvertReq() : AppBusiBirthdateConvertReq(nullptr) {}
  virtual ~AppBusiBirthdateConvertReq();
  explicit constexpr AppBusiBirthdateConvertReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppBusiBirthdateConvertReq(const AppBusiBirthdateConvertReq& from);
  AppBusiBirthdateConvertReq(AppBusiBirthdateConvertReq&& from) noexcept
    : AppBusiBirthdateConvertReq() {
    *this = ::std::move(from);
  }

  inline AppBusiBirthdateConvertReq& operator=(const AppBusiBirthdateConvertReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppBusiBirthdateConvertReq& operator=(AppBusiBirthdateConvertReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AppBusiBirthdateConvertReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppBusiBirthdateConvertReq* internal_default_instance() {
    return reinterpret_cast<const AppBusiBirthdateConvertReq*>(
               &_AppBusiBirthdateConvertReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AppBusiBirthdateConvertReq& a, AppBusiBirthdateConvertReq& b) {
    a.Swap(&b);
  }
  inline void Swap(AppBusiBirthdateConvertReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppBusiBirthdateConvertReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AppBusiBirthdateConvertReq* New() const final {
    return CreateMaybeMessage<AppBusiBirthdateConvertReq>(nullptr);
  }

  AppBusiBirthdateConvertReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AppBusiBirthdateConvertReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AppBusiBirthdateConvertReq& from);
  void MergeFrom(const AppBusiBirthdateConvertReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppBusiBirthdateConvertReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "trpc.app.AppBusiBirthdateConvertReq";
  }
  protected:
  explicit AppBusiBirthdateConvertReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_app_5fbusi_5fitg_5fserver_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBirthdateFieldNumber = 1,
  };
  // string birthdate = 1;
  void clear_birthdate();
  const std::string& birthdate() const;
  void set_birthdate(const std::string& value);
  void set_birthdate(std::string&& value);
  void set_birthdate(const char* value);
  void set_birthdate(const char* value, size_t size);
  std::string* mutable_birthdate();
  std::string* release_birthdate();
  void set_allocated_birthdate(std::string* birthdate);
  private:
  const std::string& _internal_birthdate() const;
  void _internal_set_birthdate(const std::string& value);
  std::string* _internal_mutable_birthdate();
  public:

  // @@protoc_insertion_point(class_scope:trpc.app.AppBusiBirthdateConvertReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr birthdate_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_app_5fbusi_5fitg_5fserver_2eproto;
};
// -------------------------------------------------------------------

class AppBusiBirthdateConvertRsp PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:trpc.app.AppBusiBirthdateConvertRsp) */ {
 public:
  inline AppBusiBirthdateConvertRsp() : AppBusiBirthdateConvertRsp(nullptr) {}
  virtual ~AppBusiBirthdateConvertRsp();
  explicit constexpr AppBusiBirthdateConvertRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppBusiBirthdateConvertRsp(const AppBusiBirthdateConvertRsp& from);
  AppBusiBirthdateConvertRsp(AppBusiBirthdateConvertRsp&& from) noexcept
    : AppBusiBirthdateConvertRsp() {
    *this = ::std::move(from);
  }

  inline AppBusiBirthdateConvertRsp& operator=(const AppBusiBirthdateConvertRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppBusiBirthdateConvertRsp& operator=(AppBusiBirthdateConvertRsp&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AppBusiBirthdateConvertRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppBusiBirthdateConvertRsp* internal_default_instance() {
    return reinterpret_cast<const AppBusiBirthdateConvertRsp*>(
               &_AppBusiBirthdateConvertRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AppBusiBirthdateConvertRsp& a, AppBusiBirthdateConvertRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(AppBusiBirthdateConvertRsp* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppBusiBirthdateConvertRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AppBusiBirthdateConvertRsp* New() const final {
    return CreateMaybeMessage<AppBusiBirthdateConvertRsp>(nullptr);
  }

  AppBusiBirthdateConvertRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AppBusiBirthdateConvertRsp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AppBusiBirthdateConvertRsp& from);
  void MergeFrom(const AppBusiBirthdateConvertRsp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppBusiBirthdateConvertRsp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "trpc.app.AppBusiBirthdateConvertRsp";
  }
  protected:
  explicit AppBusiBirthdateConvertRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_app_5fbusi_5fitg_5fserver_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGzIdxsFieldNumber = 4,
    kGzNamesFieldNumber = 5,
    kBirthdateFieldNumber = 1,
    kStNameFieldNumber = 3,
    kStIdxFieldNumber = 2,
  };
  // repeated uint32 gz_idxs = 4;
  int gz_idxs_size() const;
  private:
  int _internal_gz_idxs_size() const;
  public:
  void clear_gz_idxs();
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_gz_idxs(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
      _internal_gz_idxs() const;
  void _internal_add_gz_idxs(::PROTOBUF_NAMESPACE_ID::uint32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
      _internal_mutable_gz_idxs();
  public:
  ::PROTOBUF_NAMESPACE_ID::uint32 gz_idxs(int index) const;
  void set_gz_idxs(int index, ::PROTOBUF_NAMESPACE_ID::uint32 value);
  void add_gz_idxs(::PROTOBUF_NAMESPACE_ID::uint32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
      gz_idxs() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
      mutable_gz_idxs();

  // repeated string gz_names = 5;
  int gz_names_size() const;
  private:
  int _internal_gz_names_size() const;
  public:
  void clear_gz_names();
  const std::string& gz_names(int index) const;
  std::string* mutable_gz_names(int index);
  void set_gz_names(int index, const std::string& value);
  void set_gz_names(int index, std::string&& value);
  void set_gz_names(int index, const char* value);
  void set_gz_names(int index, const char* value, size_t size);
  std::string* add_gz_names();
  void add_gz_names(const std::string& value);
  void add_gz_names(std::string&& value);
  void add_gz_names(const char* value);
  void add_gz_names(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& gz_names() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_gz_names();
  private:
  const std::string& _internal_gz_names(int index) const;
  std::string* _internal_add_gz_names();
  public:

  // string birthdate = 1;
  void clear_birthdate();
  const std::string& birthdate() const;
  void set_birthdate(const std::string& value);
  void set_birthdate(std::string&& value);
  void set_birthdate(const char* value);
  void set_birthdate(const char* value, size_t size);
  std::string* mutable_birthdate();
  std::string* release_birthdate();
  void set_allocated_birthdate(std::string* birthdate);
  private:
  const std::string& _internal_birthdate() const;
  void _internal_set_birthdate(const std::string& value);
  std::string* _internal_mutable_birthdate();
  public:

  // string st_name = 3;
  void clear_st_name();
  const std::string& st_name() const;
  void set_st_name(const std::string& value);
  void set_st_name(std::string&& value);
  void set_st_name(const char* value);
  void set_st_name(const char* value, size_t size);
  std::string* mutable_st_name();
  std::string* release_st_name();
  void set_allocated_st_name(std::string* st_name);
  private:
  const std::string& _internal_st_name() const;
  void _internal_set_st_name(const std::string& value);
  std::string* _internal_mutable_st_name();
  public:

  // uint32 st_idx = 2;
  void clear_st_idx();
  ::PROTOBUF_NAMESPACE_ID::uint32 st_idx() const;
  void set_st_idx(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_st_idx() const;
  void _internal_set_st_idx(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:trpc.app.AppBusiBirthdateConvertRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 > gz_idxs_;
  mutable std::atomic<int> _gz_idxs_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> gz_names_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr birthdate_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr st_name_;
  ::PROTOBUF_NAMESPACE_ID::uint32 st_idx_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_app_5fbusi_5fitg_5fserver_2eproto;
};
// -------------------------------------------------------------------

class AppBusiBaseAuguryReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:trpc.app.AppBusiBaseAuguryReq) */ {
 public:
  inline AppBusiBaseAuguryReq() : AppBusiBaseAuguryReq(nullptr) {}
  virtual ~AppBusiBaseAuguryReq();
  explicit constexpr AppBusiBaseAuguryReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppBusiBaseAuguryReq(const AppBusiBaseAuguryReq& from);
  AppBusiBaseAuguryReq(AppBusiBaseAuguryReq&& from) noexcept
    : AppBusiBaseAuguryReq() {
    *this = ::std::move(from);
  }

  inline AppBusiBaseAuguryReq& operator=(const AppBusiBaseAuguryReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppBusiBaseAuguryReq& operator=(AppBusiBaseAuguryReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AppBusiBaseAuguryReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppBusiBaseAuguryReq* internal_default_instance() {
    return reinterpret_cast<const AppBusiBaseAuguryReq*>(
               &_AppBusiBaseAuguryReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AppBusiBaseAuguryReq& a, AppBusiBaseAuguryReq& b) {
    a.Swap(&b);
  }
  inline void Swap(AppBusiBaseAuguryReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppBusiBaseAuguryReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AppBusiBaseAuguryReq* New() const final {
    return CreateMaybeMessage<AppBusiBaseAuguryReq>(nullptr);
  }

  AppBusiBaseAuguryReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AppBusiBaseAuguryReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AppBusiBaseAuguryReq& from);
  void MergeFrom(const AppBusiBaseAuguryReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppBusiBaseAuguryReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "trpc.app.AppBusiBaseAuguryReq";
  }
  protected:
  explicit AppBusiBaseAuguryReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_app_5fbusi_5fitg_5fserver_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBirthdateFieldNumber = 1,
  };
  // string birthdate = 1;
  void clear_birthdate();
  const std::string& birthdate() const;
  void set_birthdate(const std::string& value);
  void set_birthdate(std::string&& value);
  void set_birthdate(const char* value);
  void set_birthdate(const char* value, size_t size);
  std::string* mutable_birthdate();
  std::string* release_birthdate();
  void set_allocated_birthdate(std::string* birthdate);
  private:
  const std::string& _internal_birthdate() const;
  void _internal_set_birthdate(const std::string& value);
  std::string* _internal_mutable_birthdate();
  public:

  // @@protoc_insertion_point(class_scope:trpc.app.AppBusiBaseAuguryReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr birthdate_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_app_5fbusi_5fitg_5fserver_2eproto;
};
// -------------------------------------------------------------------

class AppBusiBaseAuguryRsp PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:trpc.app.AppBusiBaseAuguryRsp) */ {
 public:
  inline AppBusiBaseAuguryRsp() : AppBusiBaseAuguryRsp(nullptr) {}
  virtual ~AppBusiBaseAuguryRsp();
  explicit constexpr AppBusiBaseAuguryRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppBusiBaseAuguryRsp(const AppBusiBaseAuguryRsp& from);
  AppBusiBaseAuguryRsp(AppBusiBaseAuguryRsp&& from) noexcept
    : AppBusiBaseAuguryRsp() {
    *this = ::std::move(from);
  }

  inline AppBusiBaseAuguryRsp& operator=(const AppBusiBaseAuguryRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppBusiBaseAuguryRsp& operator=(AppBusiBaseAuguryRsp&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AppBusiBaseAuguryRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppBusiBaseAuguryRsp* internal_default_instance() {
    return reinterpret_cast<const AppBusiBaseAuguryRsp*>(
               &_AppBusiBaseAuguryRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(AppBusiBaseAuguryRsp& a, AppBusiBaseAuguryRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(AppBusiBaseAuguryRsp* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppBusiBaseAuguryRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AppBusiBaseAuguryRsp* New() const final {
    return CreateMaybeMessage<AppBusiBaseAuguryRsp>(nullptr);
  }

  AppBusiBaseAuguryRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AppBusiBaseAuguryRsp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AppBusiBaseAuguryRsp& from);
  void MergeFrom(const AppBusiBaseAuguryRsp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppBusiBaseAuguryRsp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "trpc.app.AppBusiBaseAuguryRsp";
  }
  protected:
  explicit AppBusiBaseAuguryRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_app_5fbusi_5fitg_5fserver_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKmZIdxsFieldNumber = 1,
    kKmZNamesFieldNumber = 2,
    kMgNameFieldNumber = 4,
    kMgXNameFieldNumber = 5,
    kMgIdxFieldNumber = 3,
  };
  // repeated uint32 km_z_idxs = 1;
  int km_z_idxs_size() const;
  private:
  int _internal_km_z_idxs_size() const;
  public:
  void clear_km_z_idxs();
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_km_z_idxs(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
      _internal_km_z_idxs() const;
  void _internal_add_km_z_idxs(::PROTOBUF_NAMESPACE_ID::uint32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
      _internal_mutable_km_z_idxs();
  public:
  ::PROTOBUF_NAMESPACE_ID::uint32 km_z_idxs(int index) const;
  void set_km_z_idxs(int index, ::PROTOBUF_NAMESPACE_ID::uint32 value);
  void add_km_z_idxs(::PROTOBUF_NAMESPACE_ID::uint32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
      km_z_idxs() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
      mutable_km_z_idxs();

  // repeated string km_z_names = 2;
  int km_z_names_size() const;
  private:
  int _internal_km_z_names_size() const;
  public:
  void clear_km_z_names();
  const std::string& km_z_names(int index) const;
  std::string* mutable_km_z_names(int index);
  void set_km_z_names(int index, const std::string& value);
  void set_km_z_names(int index, std::string&& value);
  void set_km_z_names(int index, const char* value);
  void set_km_z_names(int index, const char* value, size_t size);
  std::string* add_km_z_names();
  void add_km_z_names(const std::string& value);
  void add_km_z_names(std::string&& value);
  void add_km_z_names(const char* value);
  void add_km_z_names(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& km_z_names() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_km_z_names();
  private:
  const std::string& _internal_km_z_names(int index) const;
  std::string* _internal_add_km_z_names();
  public:

  // string mg_name = 4;
  void clear_mg_name();
  const std::string& mg_name() const;
  void set_mg_name(const std::string& value);
  void set_mg_name(std::string&& value);
  void set_mg_name(const char* value);
  void set_mg_name(const char* value, size_t size);
  std::string* mutable_mg_name();
  std::string* release_mg_name();
  void set_allocated_mg_name(std::string* mg_name);
  private:
  const std::string& _internal_mg_name() const;
  void _internal_set_mg_name(const std::string& value);
  std::string* _internal_mutable_mg_name();
  public:

  // string mg_x_name = 5;
  void clear_mg_x_name();
  const std::string& mg_x_name() const;
  void set_mg_x_name(const std::string& value);
  void set_mg_x_name(std::string&& value);
  void set_mg_x_name(const char* value);
  void set_mg_x_name(const char* value, size_t size);
  std::string* mutable_mg_x_name();
  std::string* release_mg_x_name();
  void set_allocated_mg_x_name(std::string* mg_x_name);
  private:
  const std::string& _internal_mg_x_name() const;
  void _internal_set_mg_x_name(const std::string& value);
  std::string* _internal_mutable_mg_x_name();
  public:

  // uint32 mg_idx = 3;
  void clear_mg_idx();
  ::PROTOBUF_NAMESPACE_ID::uint32 mg_idx() const;
  void set_mg_idx(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_mg_idx() const;
  void _internal_set_mg_idx(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:trpc.app.AppBusiBaseAuguryRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 > km_z_idxs_;
  mutable std::atomic<int> _km_z_idxs_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> km_z_names_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mg_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mg_x_name_;
  ::PROTOBUF_NAMESPACE_ID::uint32 mg_idx_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_app_5fbusi_5fitg_5fserver_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AppBusiBirthdateConvertReq

// string birthdate = 1;
inline void AppBusiBirthdateConvertReq::clear_birthdate() {
  birthdate_.ClearToEmpty();
}
inline const std::string& AppBusiBirthdateConvertReq::birthdate() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBirthdateConvertReq.birthdate)
  return _internal_birthdate();
}
inline void AppBusiBirthdateConvertReq::set_birthdate(const std::string& value) {
  _internal_set_birthdate(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBirthdateConvertReq.birthdate)
}
inline std::string* AppBusiBirthdateConvertReq::mutable_birthdate() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppBusiBirthdateConvertReq.birthdate)
  return _internal_mutable_birthdate();
}
inline const std::string& AppBusiBirthdateConvertReq::_internal_birthdate() const {
  return birthdate_.Get();
}
inline void AppBusiBirthdateConvertReq::_internal_set_birthdate(const std::string& value) {
  
  birthdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppBusiBirthdateConvertReq::set_birthdate(std::string&& value) {
  
  birthdate_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppBusiBirthdateConvertReq.birthdate)
}
inline void AppBusiBirthdateConvertReq::set_birthdate(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  birthdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppBusiBirthdateConvertReq.birthdate)
}
inline void AppBusiBirthdateConvertReq::set_birthdate(const char* value,
    size_t size) {
  
  birthdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppBusiBirthdateConvertReq.birthdate)
}
inline std::string* AppBusiBirthdateConvertReq::_internal_mutable_birthdate() {
  
  return birthdate_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppBusiBirthdateConvertReq::release_birthdate() {
  // @@protoc_insertion_point(field_release:trpc.app.AppBusiBirthdateConvertReq.birthdate)
  return birthdate_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppBusiBirthdateConvertReq::set_allocated_birthdate(std::string* birthdate) {
  if (birthdate != nullptr) {
    
  } else {
    
  }
  birthdate_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), birthdate,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppBusiBirthdateConvertReq.birthdate)
}

// -------------------------------------------------------------------

// AppBusiBirthdateConvertRsp

// string birthdate = 1;
inline void AppBusiBirthdateConvertRsp::clear_birthdate() {
  birthdate_.ClearToEmpty();
}
inline const std::string& AppBusiBirthdateConvertRsp::birthdate() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
  return _internal_birthdate();
}
inline void AppBusiBirthdateConvertRsp::set_birthdate(const std::string& value) {
  _internal_set_birthdate(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
}
inline std::string* AppBusiBirthdateConvertRsp::mutable_birthdate() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
  return _internal_mutable_birthdate();
}
inline const std::string& AppBusiBirthdateConvertRsp::_internal_birthdate() const {
  return birthdate_.Get();
}
inline void AppBusiBirthdateConvertRsp::_internal_set_birthdate(const std::string& value) {
  
  birthdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppBusiBirthdateConvertRsp::set_birthdate(std::string&& value) {
  
  birthdate_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
}
inline void AppBusiBirthdateConvertRsp::set_birthdate(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  birthdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
}
inline void AppBusiBirthdateConvertRsp::set_birthdate(const char* value,
    size_t size) {
  
  birthdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
}
inline std::string* AppBusiBirthdateConvertRsp::_internal_mutable_birthdate() {
  
  return birthdate_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppBusiBirthdateConvertRsp::release_birthdate() {
  // @@protoc_insertion_point(field_release:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
  return birthdate_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppBusiBirthdateConvertRsp::set_allocated_birthdate(std::string* birthdate) {
  if (birthdate != nullptr) {
    
  } else {
    
  }
  birthdate_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), birthdate,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
}

// uint32 st_idx = 2;
inline void AppBusiBirthdateConvertRsp::clear_st_idx() {
  st_idx_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AppBusiBirthdateConvertRsp::_internal_st_idx() const {
  return st_idx_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AppBusiBirthdateConvertRsp::st_idx() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBirthdateConvertRsp.st_idx)
  return _internal_st_idx();
}
inline void AppBusiBirthdateConvertRsp::_internal_set_st_idx(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  st_idx_ = value;
}
inline void AppBusiBirthdateConvertRsp::set_st_idx(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_st_idx(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBirthdateConvertRsp.st_idx)
}

// string st_name = 3;
inline void AppBusiBirthdateConvertRsp::clear_st_name() {
  st_name_.ClearToEmpty();
}
inline const std::string& AppBusiBirthdateConvertRsp::st_name() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBirthdateConvertRsp.st_name)
  return _internal_st_name();
}
inline void AppBusiBirthdateConvertRsp::set_st_name(const std::string& value) {
  _internal_set_st_name(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBirthdateConvertRsp.st_name)
}
inline std::string* AppBusiBirthdateConvertRsp::mutable_st_name() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppBusiBirthdateConvertRsp.st_name)
  return _internal_mutable_st_name();
}
inline const std::string& AppBusiBirthdateConvertRsp::_internal_st_name() const {
  return st_name_.Get();
}
inline void AppBusiBirthdateConvertRsp::_internal_set_st_name(const std::string& value) {
  
  st_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppBusiBirthdateConvertRsp::set_st_name(std::string&& value) {
  
  st_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppBusiBirthdateConvertRsp.st_name)
}
inline void AppBusiBirthdateConvertRsp::set_st_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  st_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppBusiBirthdateConvertRsp.st_name)
}
inline void AppBusiBirthdateConvertRsp::set_st_name(const char* value,
    size_t size) {
  
  st_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppBusiBirthdateConvertRsp.st_name)
}
inline std::string* AppBusiBirthdateConvertRsp::_internal_mutable_st_name() {
  
  return st_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppBusiBirthdateConvertRsp::release_st_name() {
  // @@protoc_insertion_point(field_release:trpc.app.AppBusiBirthdateConvertRsp.st_name)
  return st_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppBusiBirthdateConvertRsp::set_allocated_st_name(std::string* st_name) {
  if (st_name != nullptr) {
    
  } else {
    
  }
  st_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), st_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppBusiBirthdateConvertRsp.st_name)
}

// repeated uint32 gz_idxs = 4;
inline int AppBusiBirthdateConvertRsp::_internal_gz_idxs_size() const {
  return gz_idxs_.size();
}
inline int AppBusiBirthdateConvertRsp::gz_idxs_size() const {
  return _internal_gz_idxs_size();
}
inline void AppBusiBirthdateConvertRsp::clear_gz_idxs() {
  gz_idxs_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AppBusiBirthdateConvertRsp::_internal_gz_idxs(int index) const {
  return gz_idxs_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AppBusiBirthdateConvertRsp::gz_idxs(int index) const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBirthdateConvertRsp.gz_idxs)
  return _internal_gz_idxs(index);
}
inline void AppBusiBirthdateConvertRsp::set_gz_idxs(int index, ::PROTOBUF_NAMESPACE_ID::uint32 value) {
  gz_idxs_.Set(index, value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBirthdateConvertRsp.gz_idxs)
}
inline void AppBusiBirthdateConvertRsp::_internal_add_gz_idxs(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  gz_idxs_.Add(value);
}
inline void AppBusiBirthdateConvertRsp::add_gz_idxs(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_add_gz_idxs(value);
  // @@protoc_insertion_point(field_add:trpc.app.AppBusiBirthdateConvertRsp.gz_idxs)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
AppBusiBirthdateConvertRsp::_internal_gz_idxs() const {
  return gz_idxs_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
AppBusiBirthdateConvertRsp::gz_idxs() const {
  // @@protoc_insertion_point(field_list:trpc.app.AppBusiBirthdateConvertRsp.gz_idxs)
  return _internal_gz_idxs();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
AppBusiBirthdateConvertRsp::_internal_mutable_gz_idxs() {
  return &gz_idxs_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
AppBusiBirthdateConvertRsp::mutable_gz_idxs() {
  // @@protoc_insertion_point(field_mutable_list:trpc.app.AppBusiBirthdateConvertRsp.gz_idxs)
  return _internal_mutable_gz_idxs();
}

// repeated string gz_names = 5;
inline int AppBusiBirthdateConvertRsp::_internal_gz_names_size() const {
  return gz_names_.size();
}
inline int AppBusiBirthdateConvertRsp::gz_names_size() const {
  return _internal_gz_names_size();
}
inline void AppBusiBirthdateConvertRsp::clear_gz_names() {
  gz_names_.Clear();
}
inline std::string* AppBusiBirthdateConvertRsp::add_gz_names() {
  // @@protoc_insertion_point(field_add_mutable:trpc.app.AppBusiBirthdateConvertRsp.gz_names)
  return _internal_add_gz_names();
}
inline const std::string& AppBusiBirthdateConvertRsp::_internal_gz_names(int index) const {
  return gz_names_.Get(index);
}
inline const std::string& AppBusiBirthdateConvertRsp::gz_names(int index) const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBirthdateConvertRsp.gz_names)
  return _internal_gz_names(index);
}
inline std::string* AppBusiBirthdateConvertRsp::mutable_gz_names(int index) {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppBusiBirthdateConvertRsp.gz_names)
  return gz_names_.Mutable(index);
}
inline void AppBusiBirthdateConvertRsp::set_gz_names(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBirthdateConvertRsp.gz_names)
  gz_names_.Mutable(index)->assign(value);
}
inline void AppBusiBirthdateConvertRsp::set_gz_names(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBirthdateConvertRsp.gz_names)
  gz_names_.Mutable(index)->assign(std::move(value));
}
inline void AppBusiBirthdateConvertRsp::set_gz_names(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  gz_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:trpc.app.AppBusiBirthdateConvertRsp.gz_names)
}
inline void AppBusiBirthdateConvertRsp::set_gz_names(int index, const char* value, size_t size) {
  gz_names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppBusiBirthdateConvertRsp.gz_names)
}
inline std::string* AppBusiBirthdateConvertRsp::_internal_add_gz_names() {
  return gz_names_.Add();
}
inline void AppBusiBirthdateConvertRsp::add_gz_names(const std::string& value) {
  gz_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:trpc.app.AppBusiBirthdateConvertRsp.gz_names)
}
inline void AppBusiBirthdateConvertRsp::add_gz_names(std::string&& value) {
  gz_names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:trpc.app.AppBusiBirthdateConvertRsp.gz_names)
}
inline void AppBusiBirthdateConvertRsp::add_gz_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  gz_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:trpc.app.AppBusiBirthdateConvertRsp.gz_names)
}
inline void AppBusiBirthdateConvertRsp::add_gz_names(const char* value, size_t size) {
  gz_names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:trpc.app.AppBusiBirthdateConvertRsp.gz_names)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
AppBusiBirthdateConvertRsp::gz_names() const {
  // @@protoc_insertion_point(field_list:trpc.app.AppBusiBirthdateConvertRsp.gz_names)
  return gz_names_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
AppBusiBirthdateConvertRsp::mutable_gz_names() {
  // @@protoc_insertion_point(field_mutable_list:trpc.app.AppBusiBirthdateConvertRsp.gz_names)
  return &gz_names_;
}

// -------------------------------------------------------------------

// AppBusiBaseAuguryReq

// string birthdate = 1;
inline void AppBusiBaseAuguryReq::clear_birthdate() {
  birthdate_.ClearToEmpty();
}
inline const std::string& AppBusiBaseAuguryReq::birthdate() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBaseAuguryReq.birthdate)
  return _internal_birthdate();
}
inline void AppBusiBaseAuguryReq::set_birthdate(const std::string& value) {
  _internal_set_birthdate(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBaseAuguryReq.birthdate)
}
inline std::string* AppBusiBaseAuguryReq::mutable_birthdate() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppBusiBaseAuguryReq.birthdate)
  return _internal_mutable_birthdate();
}
inline const std::string& AppBusiBaseAuguryReq::_internal_birthdate() const {
  return birthdate_.Get();
}
inline void AppBusiBaseAuguryReq::_internal_set_birthdate(const std::string& value) {
  
  birthdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppBusiBaseAuguryReq::set_birthdate(std::string&& value) {
  
  birthdate_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppBusiBaseAuguryReq.birthdate)
}
inline void AppBusiBaseAuguryReq::set_birthdate(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  birthdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppBusiBaseAuguryReq.birthdate)
}
inline void AppBusiBaseAuguryReq::set_birthdate(const char* value,
    size_t size) {
  
  birthdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppBusiBaseAuguryReq.birthdate)
}
inline std::string* AppBusiBaseAuguryReq::_internal_mutable_birthdate() {
  
  return birthdate_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppBusiBaseAuguryReq::release_birthdate() {
  // @@protoc_insertion_point(field_release:trpc.app.AppBusiBaseAuguryReq.birthdate)
  return birthdate_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppBusiBaseAuguryReq::set_allocated_birthdate(std::string* birthdate) {
  if (birthdate != nullptr) {
    
  } else {
    
  }
  birthdate_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), birthdate,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppBusiBaseAuguryReq.birthdate)
}

// -------------------------------------------------------------------

// AppBusiBaseAuguryRsp

// repeated uint32 km_z_idxs = 1;
inline int AppBusiBaseAuguryRsp::_internal_km_z_idxs_size() const {
  return km_z_idxs_.size();
}
inline int AppBusiBaseAuguryRsp::km_z_idxs_size() const {
  return _internal_km_z_idxs_size();
}
inline void AppBusiBaseAuguryRsp::clear_km_z_idxs() {
  km_z_idxs_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AppBusiBaseAuguryRsp::_internal_km_z_idxs(int index) const {
  return km_z_idxs_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AppBusiBaseAuguryRsp::km_z_idxs(int index) const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBaseAuguryRsp.km_z_idxs)
  return _internal_km_z_idxs(index);
}
inline void AppBusiBaseAuguryRsp::set_km_z_idxs(int index, ::PROTOBUF_NAMESPACE_ID::uint32 value) {
  km_z_idxs_.Set(index, value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBaseAuguryRsp.km_z_idxs)
}
inline void AppBusiBaseAuguryRsp::_internal_add_km_z_idxs(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  km_z_idxs_.Add(value);
}
inline void AppBusiBaseAuguryRsp::add_km_z_idxs(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_add_km_z_idxs(value);
  // @@protoc_insertion_point(field_add:trpc.app.AppBusiBaseAuguryRsp.km_z_idxs)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
AppBusiBaseAuguryRsp::_internal_km_z_idxs() const {
  return km_z_idxs_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
AppBusiBaseAuguryRsp::km_z_idxs() const {
  // @@protoc_insertion_point(field_list:trpc.app.AppBusiBaseAuguryRsp.km_z_idxs)
  return _internal_km_z_idxs();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
AppBusiBaseAuguryRsp::_internal_mutable_km_z_idxs() {
  return &km_z_idxs_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
AppBusiBaseAuguryRsp::mutable_km_z_idxs() {
  // @@protoc_insertion_point(field_mutable_list:trpc.app.AppBusiBaseAuguryRsp.km_z_idxs)
  return _internal_mutable_km_z_idxs();
}

// repeated string km_z_names = 2;
inline int AppBusiBaseAuguryRsp::_internal_km_z_names_size() const {
  return km_z_names_.size();
}
inline int AppBusiBaseAuguryRsp::km_z_names_size() const {
  return _internal_km_z_names_size();
}
inline void AppBusiBaseAuguryRsp::clear_km_z_names() {
  km_z_names_.Clear();
}
inline std::string* AppBusiBaseAuguryRsp::add_km_z_names() {
  // @@protoc_insertion_point(field_add_mutable:trpc.app.AppBusiBaseAuguryRsp.km_z_names)
  return _internal_add_km_z_names();
}
inline const std::string& AppBusiBaseAuguryRsp::_internal_km_z_names(int index) const {
  return km_z_names_.Get(index);
}
inline const std::string& AppBusiBaseAuguryRsp::km_z_names(int index) const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBaseAuguryRsp.km_z_names)
  return _internal_km_z_names(index);
}
inline std::string* AppBusiBaseAuguryRsp::mutable_km_z_names(int index) {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppBusiBaseAuguryRsp.km_z_names)
  return km_z_names_.Mutable(index);
}
inline void AppBusiBaseAuguryRsp::set_km_z_names(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBaseAuguryRsp.km_z_names)
  km_z_names_.Mutable(index)->assign(value);
}
inline void AppBusiBaseAuguryRsp::set_km_z_names(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBaseAuguryRsp.km_z_names)
  km_z_names_.Mutable(index)->assign(std::move(value));
}
inline void AppBusiBaseAuguryRsp::set_km_z_names(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  km_z_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:trpc.app.AppBusiBaseAuguryRsp.km_z_names)
}
inline void AppBusiBaseAuguryRsp::set_km_z_names(int index, const char* value, size_t size) {
  km_z_names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppBusiBaseAuguryRsp.km_z_names)
}
inline std::string* AppBusiBaseAuguryRsp::_internal_add_km_z_names() {
  return km_z_names_.Add();
}
inline void AppBusiBaseAuguryRsp::add_km_z_names(const std::string& value) {
  km_z_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:trpc.app.AppBusiBaseAuguryRsp.km_z_names)
}
inline void AppBusiBaseAuguryRsp::add_km_z_names(std::string&& value) {
  km_z_names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:trpc.app.AppBusiBaseAuguryRsp.km_z_names)
}
inline void AppBusiBaseAuguryRsp::add_km_z_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  km_z_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:trpc.app.AppBusiBaseAuguryRsp.km_z_names)
}
inline void AppBusiBaseAuguryRsp::add_km_z_names(const char* value, size_t size) {
  km_z_names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:trpc.app.AppBusiBaseAuguryRsp.km_z_names)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
AppBusiBaseAuguryRsp::km_z_names() const {
  // @@protoc_insertion_point(field_list:trpc.app.AppBusiBaseAuguryRsp.km_z_names)
  return km_z_names_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
AppBusiBaseAuguryRsp::mutable_km_z_names() {
  // @@protoc_insertion_point(field_mutable_list:trpc.app.AppBusiBaseAuguryRsp.km_z_names)
  return &km_z_names_;
}

// uint32 mg_idx = 3;
inline void AppBusiBaseAuguryRsp::clear_mg_idx() {
  mg_idx_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AppBusiBaseAuguryRsp::_internal_mg_idx() const {
  return mg_idx_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AppBusiBaseAuguryRsp::mg_idx() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBaseAuguryRsp.mg_idx)
  return _internal_mg_idx();
}
inline void AppBusiBaseAuguryRsp::_internal_set_mg_idx(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  mg_idx_ = value;
}
inline void AppBusiBaseAuguryRsp::set_mg_idx(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_mg_idx(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBaseAuguryRsp.mg_idx)
}

// string mg_name = 4;
inline void AppBusiBaseAuguryRsp::clear_mg_name() {
  mg_name_.ClearToEmpty();
}
inline const std::string& AppBusiBaseAuguryRsp::mg_name() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBaseAuguryRsp.mg_name)
  return _internal_mg_name();
}
inline void AppBusiBaseAuguryRsp::set_mg_name(const std::string& value) {
  _internal_set_mg_name(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBaseAuguryRsp.mg_name)
}
inline std::string* AppBusiBaseAuguryRsp::mutable_mg_name() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppBusiBaseAuguryRsp.mg_name)
  return _internal_mutable_mg_name();
}
inline const std::string& AppBusiBaseAuguryRsp::_internal_mg_name() const {
  return mg_name_.Get();
}
inline void AppBusiBaseAuguryRsp::_internal_set_mg_name(const std::string& value) {
  
  mg_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppBusiBaseAuguryRsp::set_mg_name(std::string&& value) {
  
  mg_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppBusiBaseAuguryRsp.mg_name)
}
inline void AppBusiBaseAuguryRsp::set_mg_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  mg_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppBusiBaseAuguryRsp.mg_name)
}
inline void AppBusiBaseAuguryRsp::set_mg_name(const char* value,
    size_t size) {
  
  mg_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppBusiBaseAuguryRsp.mg_name)
}
inline std::string* AppBusiBaseAuguryRsp::_internal_mutable_mg_name() {
  
  return mg_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppBusiBaseAuguryRsp::release_mg_name() {
  // @@protoc_insertion_point(field_release:trpc.app.AppBusiBaseAuguryRsp.mg_name)
  return mg_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppBusiBaseAuguryRsp::set_allocated_mg_name(std::string* mg_name) {
  if (mg_name != nullptr) {
    
  } else {
    
  }
  mg_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), mg_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppBusiBaseAuguryRsp.mg_name)
}

// string mg_x_name = 5;
inline void AppBusiBaseAuguryRsp::clear_mg_x_name() {
  mg_x_name_.ClearToEmpty();
}
inline const std::string& AppBusiBaseAuguryRsp::mg_x_name() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBaseAuguryRsp.mg_x_name)
  return _internal_mg_x_name();
}
inline void AppBusiBaseAuguryRsp::set_mg_x_name(const std::string& value) {
  _internal_set_mg_x_name(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBaseAuguryRsp.mg_x_name)
}
inline std::string* AppBusiBaseAuguryRsp::mutable_mg_x_name() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppBusiBaseAuguryRsp.mg_x_name)
  return _internal_mutable_mg_x_name();
}
inline const std::string& AppBusiBaseAuguryRsp::_internal_mg_x_name() const {
  return mg_x_name_.Get();
}
inline void AppBusiBaseAuguryRsp::_internal_set_mg_x_name(const std::string& value) {
  
  mg_x_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppBusiBaseAuguryRsp::set_mg_x_name(std::string&& value) {
  
  mg_x_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppBusiBaseAuguryRsp.mg_x_name)
}
inline void AppBusiBaseAuguryRsp::set_mg_x_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  mg_x_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppBusiBaseAuguryRsp.mg_x_name)
}
inline void AppBusiBaseAuguryRsp::set_mg_x_name(const char* value,
    size_t size) {
  
  mg_x_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppBusiBaseAuguryRsp.mg_x_name)
}
inline std::string* AppBusiBaseAuguryRsp::_internal_mutable_mg_x_name() {
  
  return mg_x_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppBusiBaseAuguryRsp::release_mg_x_name() {
  // @@protoc_insertion_point(field_release:trpc.app.AppBusiBaseAuguryRsp.mg_x_name)
  return mg_x_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppBusiBaseAuguryRsp::set_allocated_mg_x_name(std::string* mg_x_name) {
  if (mg_x_name != nullptr) {
    
  } else {
    
  }
  mg_x_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), mg_x_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppBusiBaseAuguryRsp.mg_x_name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace app
}  // namespace trpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_app_5fbusi_5fitg_5fserver_2eproto
