//
// This file was generated by trpc_cpp_plugin which is a self-defined pb compiler plugin, do not edit it!!!
// All rights reserved by Tencent Corporation
//

#include "app_user_itg_server.trpc.pb.h"

#include "trpc/server/rpc_async_method_handler.h"
#include "trpc/server/rpc_method_handler.h"

namespace trpc {
namespace app {

static const std::vector<std::vector<std::string_view>> AppUserItgService_method_names = {
  {"/trpc.app.AppUserItgService/AppUserRegisterHandler"},
  {"/trpc.app.AppUserItgService/AppUserQueryInfoHandler"},
};

AppUserItgService::AppUserItgService() {
  for (const std::string_view& method : AppUserItgService_method_names[0]) {
    AddRpcServiceMethod(new ::trpc::RpcServiceMethod(method.data(), ::trpc::MethodType::UNARY, new ::trpc::RpcMethodHandler<::trpc::app::AppUserRegisterReq, ::trpc::app::AppUserRegisterRsp>(std::bind(&AppUserItgService::AppUserRegisterHandler, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3))));
  }
  for (const std::string_view& method : AppUserItgService_method_names[1]) {
    AddRpcServiceMethod(new ::trpc::RpcServiceMethod(method.data(), ::trpc::MethodType::UNARY, new ::trpc::RpcMethodHandler<::trpc::app::AppUserQueryInfoReq, ::trpc::app::AppUserQueryInfoRsp>(std::bind(&AppUserItgService::AppUserQueryInfoHandler, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3))));
  }
}

::trpc::Status AppUserItgService::AppUserRegisterHandler(::trpc::ServerContextPtr context, const ::trpc::app::AppUserRegisterReq* request, ::trpc::app::AppUserRegisterRsp* response) {
  (void)context;
  (void)request;
  (void)response;
  return ::trpc::Status(-1, "");
}

::trpc::Status AppUserItgService::AppUserQueryInfoHandler(::trpc::ServerContextPtr context, const ::trpc::app::AppUserQueryInfoReq* request, ::trpc::app::AppUserQueryInfoRsp* response) {
  (void)context;
  (void)request;
  (void)response;
  return ::trpc::Status(-1, "");
}

AsyncAppUserItgService::AsyncAppUserItgService() : ::trpc::AsyncRpcServiceImpl() {
  for (const std::string_view& method : AppUserItgService_method_names[0]) {
    AddRpcServiceMethod(new ::trpc::RpcServiceMethod(method.data(), ::trpc::MethodType::UNARY, new ::trpc::AsyncRpcMethodHandler<::trpc::app::AppUserRegisterReq, ::trpc::app::AppUserRegisterRsp>(std::bind(&AsyncAppUserItgService::AppUserRegisterHandler, this, std::placeholders::_1, std::placeholders::_2))));
  }
  for (const std::string_view& method : AppUserItgService_method_names[1]) {
    AddRpcServiceMethod(new ::trpc::RpcServiceMethod(method.data(), ::trpc::MethodType::UNARY, new ::trpc::AsyncRpcMethodHandler<::trpc::app::AppUserQueryInfoReq, ::trpc::app::AppUserQueryInfoRsp>(std::bind(&AsyncAppUserItgService::AppUserQueryInfoHandler, this, std::placeholders::_1, std::placeholders::_2))));
  }
}

::trpc::Future<::trpc::app::AppUserRegisterRsp> AsyncAppUserItgService::AppUserRegisterHandler(const ::trpc::ServerContextPtr& context, const ::trpc::app::AppUserRegisterReq* request) {
  return ::trpc::MakeExceptionFuture<::trpc::app::AppUserRegisterRsp>(::trpc::CommonException("Unimplemented"));
}

::trpc::Future<::trpc::app::AppUserQueryInfoRsp> AsyncAppUserItgService::AppUserQueryInfoHandler(const ::trpc::ServerContextPtr& context, const ::trpc::app::AppUserQueryInfoReq* request) {
  return ::trpc::MakeExceptionFuture<::trpc::app::AppUserQueryInfoRsp>(::trpc::CommonException("Unimplemented"));
}

::trpc::Status AppUserItgServiceServiceProxy::AppUserRegisterHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserRegisterReq& request, ::trpc::app::AppUserRegisterRsp* response) {
  if (context->GetFuncName().empty()) context->SetFuncName(AppUserItgService_method_names[0][0].data());
  return UnaryInvoke<::trpc::app::AppUserRegisterReq, ::trpc::app::AppUserRegisterRsp>(context, request, response);
}

::trpc::Status AppUserItgServiceServiceProxy::AppUserQueryInfoHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserQueryInfoReq& request, ::trpc::app::AppUserQueryInfoRsp* response) {
  if (context->GetFuncName().empty()) context->SetFuncName(AppUserItgService_method_names[1][0].data());
  return UnaryInvoke<::trpc::app::AppUserQueryInfoReq, ::trpc::app::AppUserQueryInfoRsp>(context, request, response);
}

::trpc::Future<::trpc::app::AppUserRegisterRsp> AppUserItgServiceServiceProxy::AsyncAppUserRegisterHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserRegisterReq& request) {
  if (context->GetFuncName().empty()) context->SetFuncName(AppUserItgService_method_names[0][0].data());
  return AsyncUnaryInvoke<::trpc::app::AppUserRegisterReq, ::trpc::app::AppUserRegisterRsp>(context, request);
}

::trpc::Future<::trpc::app::AppUserQueryInfoRsp> AppUserItgServiceServiceProxy::AsyncAppUserQueryInfoHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserQueryInfoReq& request) {
  if (context->GetFuncName().empty()) context->SetFuncName(AppUserItgService_method_names[1][0].data());
  return AsyncUnaryInvoke<::trpc::app::AppUserQueryInfoReq, ::trpc::app::AppUserQueryInfoRsp>(context, request);
}

::trpc::Status AppUserItgServiceServiceProxy::AppUserRegisterHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserRegisterReq& request) {
  if (context->GetFuncName().empty()) context->SetFuncName(AppUserItgService_method_names[0][0].data());
  return OnewayInvoke<::trpc::app::AppUserRegisterReq>(context, request);
}

::trpc::Status AppUserItgServiceServiceProxy::AppUserQueryInfoHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserQueryInfoReq& request) {
  if (context->GetFuncName().empty()) context->SetFuncName(AppUserItgService_method_names[1][0].data());
  return OnewayInvoke<::trpc::app::AppUserQueryInfoReq>(context, request);
}

::trpc::Future<::trpc::app::AppUserRegisterRsp> AsyncAppUserItgServiceServiceProxy::AppUserRegisterHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserRegisterReq& request) {
  if (context->GetFuncName().empty()) context->SetFuncName(AppUserItgService_method_names[0][0].data());
  return AsyncUnaryInvoke<::trpc::app::AppUserRegisterReq, ::trpc::app::AppUserRegisterRsp>(context, request);
}

::trpc::Future<::trpc::app::AppUserQueryInfoRsp> AsyncAppUserItgServiceServiceProxy::AppUserQueryInfoHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserQueryInfoReq& request) {
  if (context->GetFuncName().empty()) context->SetFuncName(AppUserItgService_method_names[1][0].data());
  return AsyncUnaryInvoke<::trpc::app::AppUserQueryInfoReq, ::trpc::app::AppUserQueryInfoRsp>(context, request);
}

} // end namespace app
} // end namespace trpc