//
// This file was generated by trpc_cpp_plugin which is a self-defined pb compiler plugin, do not edit it!!!
// All rights reserved by Tencent Corporation
//

#pragma once

#include "app_user_itg_server.pb.h"

#include "trpc/client/rpc_service_proxy.h"
#include "trpc/server/rpc_service_impl.h"

namespace trpc {
namespace app {

class AppUserItgService : public ::trpc::RpcServiceImpl {
 public:
  AppUserItgService();

  virtual ::trpc::Status AppUserRegisterHandler(::trpc::ServerContextPtr context, const ::trpc::app::AppUserRegisterReq* request, ::trpc::app::AppUserRegisterRsp* response);
  virtual ::trpc::Status AppUserQueryInfoHandler(::trpc::ServerContextPtr context, const ::trpc::app::AppUserQueryInfoReq* request, ::trpc::app::AppUserQueryInfoRsp* response);
};

class AsyncAppUserItgService : public ::trpc::AsyncRpcServiceImpl {
 public:
  AsyncAppUserItgService();
  
  virtual ::trpc::Future<::trpc::app::AppUserRegisterRsp> AppUserRegisterHandler(const ::trpc::ServerContextPtr& context, const ::trpc::app::AppUserRegisterReq* request);
  virtual ::trpc::Future<::trpc::app::AppUserQueryInfoRsp> AppUserQueryInfoHandler(const ::trpc::ServerContextPtr& context, const ::trpc::app::AppUserQueryInfoReq* request);
};

class AppUserItgServiceServiceProxy : public ::trpc::RpcServiceProxy {
 public:
  virtual ::trpc::Status AppUserRegisterHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserRegisterReq& request, ::trpc::app::AppUserRegisterRsp* response);
  virtual ::trpc::Future<::trpc::app::AppUserRegisterRsp> AsyncAppUserRegisterHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserRegisterReq& request);
  // oneway, only send
  virtual ::trpc::Status AppUserRegisterHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserRegisterReq& request);
  virtual ::trpc::Status AppUserQueryInfoHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserQueryInfoReq& request, ::trpc::app::AppUserQueryInfoRsp* response);
  virtual ::trpc::Future<::trpc::app::AppUserQueryInfoRsp> AsyncAppUserQueryInfoHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserQueryInfoReq& request);
  // oneway, only send
  virtual ::trpc::Status AppUserQueryInfoHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserQueryInfoReq& request);
};

class AsyncAppUserItgServiceServiceProxy : public ::trpc::RpcServiceProxy {
 public:
  ::trpc::Future<::trpc::app::AppUserRegisterRsp> AppUserRegisterHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserRegisterReq& request);
  // TODO: one-way
  ::trpc::Future<::trpc::app::AppUserQueryInfoRsp> AppUserQueryInfoHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppUserQueryInfoReq& request);
  // TODO: one-way
};

} // end namespace app
} // end namespace trpc