// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_user_itg_server.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_app_5fuser_5fitg_5fserver_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_app_5fuser_5fitg_5fserver_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_app_5fuser_5fitg_5fserver_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_app_5fuser_5fitg_5fserver_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_app_5fuser_5fitg_5fserver_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_app_5fuser_5fitg_5fserver_2eproto_metadata_getter(int index);
namespace trpc {
namespace app {
class AppUserInfo;
struct AppUserInfoDefaultTypeInternal;
extern AppUserInfoDefaultTypeInternal _AppUserInfo_default_instance_;
class AppUserQueryInfoReq;
struct AppUserQueryInfoReqDefaultTypeInternal;
extern AppUserQueryInfoReqDefaultTypeInternal _AppUserQueryInfoReq_default_instance_;
class AppUserQueryInfoRsp;
struct AppUserQueryInfoRspDefaultTypeInternal;
extern AppUserQueryInfoRspDefaultTypeInternal _AppUserQueryInfoRsp_default_instance_;
class AppUserRegisterReq;
struct AppUserRegisterReqDefaultTypeInternal;
extern AppUserRegisterReqDefaultTypeInternal _AppUserRegisterReq_default_instance_;
class AppUserRegisterRsp;
struct AppUserRegisterRspDefaultTypeInternal;
extern AppUserRegisterRspDefaultTypeInternal _AppUserRegisterRsp_default_instance_;
}  // namespace app
}  // namespace trpc
PROTOBUF_NAMESPACE_OPEN
template<> ::trpc::app::AppUserInfo* Arena::CreateMaybeMessage<::trpc::app::AppUserInfo>(Arena*);
template<> ::trpc::app::AppUserQueryInfoReq* Arena::CreateMaybeMessage<::trpc::app::AppUserQueryInfoReq>(Arena*);
template<> ::trpc::app::AppUserQueryInfoRsp* Arena::CreateMaybeMessage<::trpc::app::AppUserQueryInfoRsp>(Arena*);
template<> ::trpc::app::AppUserRegisterReq* Arena::CreateMaybeMessage<::trpc::app::AppUserRegisterReq>(Arena*);
template<> ::trpc::app::AppUserRegisterRsp* Arena::CreateMaybeMessage<::trpc::app::AppUserRegisterRsp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace trpc {
namespace app {

// ===================================================================

class AppUserInfo PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:trpc.app.AppUserInfo) */ {
 public:
  inline AppUserInfo() : AppUserInfo(nullptr) {}
  virtual ~AppUserInfo();
  explicit constexpr AppUserInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppUserInfo(const AppUserInfo& from);
  AppUserInfo(AppUserInfo&& from) noexcept
    : AppUserInfo() {
    *this = ::std::move(from);
  }

  inline AppUserInfo& operator=(const AppUserInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppUserInfo& operator=(AppUserInfo&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AppUserInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppUserInfo* internal_default_instance() {
    return reinterpret_cast<const AppUserInfo*>(
               &_AppUserInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AppUserInfo& a, AppUserInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(AppUserInfo* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppUserInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AppUserInfo* New() const final {
    return CreateMaybeMessage<AppUserInfo>(nullptr);
  }

  AppUserInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AppUserInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AppUserInfo& from);
  void MergeFrom(const AppUserInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppUserInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "trpc.app.AppUserInfo";
  }
  protected:
  explicit AppUserInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_app_5fuser_5fitg_5fserver_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAppidFieldNumber = 1,
    kPhoneFieldNumber = 2,
    kUserNameFieldNumber = 3,
    kRegisterTimeFieldNumber = 4,
    kPasswordFieldNumber = 5,
    kIconUrlFieldNumber = 6,
  };
  // string appid = 1;
  void clear_appid();
  const std::string& appid() const;
  void set_appid(const std::string& value);
  void set_appid(std::string&& value);
  void set_appid(const char* value);
  void set_appid(const char* value, size_t size);
  std::string* mutable_appid();
  std::string* release_appid();
  void set_allocated_appid(std::string* appid);
  private:
  const std::string& _internal_appid() const;
  void _internal_set_appid(const std::string& value);
  std::string* _internal_mutable_appid();
  public:

  // string phone = 2;
  void clear_phone();
  const std::string& phone() const;
  void set_phone(const std::string& value);
  void set_phone(std::string&& value);
  void set_phone(const char* value);
  void set_phone(const char* value, size_t size);
  std::string* mutable_phone();
  std::string* release_phone();
  void set_allocated_phone(std::string* phone);
  private:
  const std::string& _internal_phone() const;
  void _internal_set_phone(const std::string& value);
  std::string* _internal_mutable_phone();
  public:

  // string user_name = 3;
  void clear_user_name();
  const std::string& user_name() const;
  void set_user_name(const std::string& value);
  void set_user_name(std::string&& value);
  void set_user_name(const char* value);
  void set_user_name(const char* value, size_t size);
  std::string* mutable_user_name();
  std::string* release_user_name();
  void set_allocated_user_name(std::string* user_name);
  private:
  const std::string& _internal_user_name() const;
  void _internal_set_user_name(const std::string& value);
  std::string* _internal_mutable_user_name();
  public:

  // string register_time = 4;
  void clear_register_time();
  const std::string& register_time() const;
  void set_register_time(const std::string& value);
  void set_register_time(std::string&& value);
  void set_register_time(const char* value);
  void set_register_time(const char* value, size_t size);
  std::string* mutable_register_time();
  std::string* release_register_time();
  void set_allocated_register_time(std::string* register_time);
  private:
  const std::string& _internal_register_time() const;
  void _internal_set_register_time(const std::string& value);
  std::string* _internal_mutable_register_time();
  public:

  // string password = 5;
  bool has_password() const;
  private:
  bool _internal_has_password() const;
  public:
  void clear_password();
  const std::string& password() const;
  void set_password(const std::string& value);
  void set_password(std::string&& value);
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  std::string* mutable_password();
  std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // string icon_url = 6;
  bool has_icon_url() const;
  private:
  bool _internal_has_icon_url() const;
  public:
  void clear_icon_url();
  const std::string& icon_url() const;
  void set_icon_url(const std::string& value);
  void set_icon_url(std::string&& value);
  void set_icon_url(const char* value);
  void set_icon_url(const char* value, size_t size);
  std::string* mutable_icon_url();
  std::string* release_icon_url();
  void set_allocated_icon_url(std::string* icon_url);
  private:
  const std::string& _internal_icon_url() const;
  void _internal_set_icon_url(const std::string& value);
  std::string* _internal_mutable_icon_url();
  public:

  // @@protoc_insertion_point(class_scope:trpc.app.AppUserInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr appid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr phone_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr register_time_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr icon_url_;
  friend struct ::TableStruct_app_5fuser_5fitg_5fserver_2eproto;
};
// -------------------------------------------------------------------

class AppUserRegisterReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:trpc.app.AppUserRegisterReq) */ {
 public:
  inline AppUserRegisterReq() : AppUserRegisterReq(nullptr) {}
  virtual ~AppUserRegisterReq();
  explicit constexpr AppUserRegisterReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppUserRegisterReq(const AppUserRegisterReq& from);
  AppUserRegisterReq(AppUserRegisterReq&& from) noexcept
    : AppUserRegisterReq() {
    *this = ::std::move(from);
  }

  inline AppUserRegisterReq& operator=(const AppUserRegisterReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppUserRegisterReq& operator=(AppUserRegisterReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AppUserRegisterReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppUserRegisterReq* internal_default_instance() {
    return reinterpret_cast<const AppUserRegisterReq*>(
               &_AppUserRegisterReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AppUserRegisterReq& a, AppUserRegisterReq& b) {
    a.Swap(&b);
  }
  inline void Swap(AppUserRegisterReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppUserRegisterReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AppUserRegisterReq* New() const final {
    return CreateMaybeMessage<AppUserRegisterReq>(nullptr);
  }

  AppUserRegisterReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AppUserRegisterReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AppUserRegisterReq& from);
  void MergeFrom(const AppUserRegisterReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppUserRegisterReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "trpc.app.AppUserRegisterReq";
  }
  protected:
  explicit AppUserRegisterReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_app_5fuser_5fitg_5fserver_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPublicKeyFieldNumber = 2,
    kUserInfoFieldNumber = 1,
  };
  // string public_key = 2;
  void clear_public_key();
  const std::string& public_key() const;
  void set_public_key(const std::string& value);
  void set_public_key(std::string&& value);
  void set_public_key(const char* value);
  void set_public_key(const char* value, size_t size);
  std::string* mutable_public_key();
  std::string* release_public_key();
  void set_allocated_public_key(std::string* public_key);
  private:
  const std::string& _internal_public_key() const;
  void _internal_set_public_key(const std::string& value);
  std::string* _internal_mutable_public_key();
  public:

  // .trpc.app.AppUserInfo user_info = 1;
  bool has_user_info() const;
  private:
  bool _internal_has_user_info() const;
  public:
  void clear_user_info();
  const ::trpc::app::AppUserInfo& user_info() const;
  ::trpc::app::AppUserInfo* release_user_info();
  ::trpc::app::AppUserInfo* mutable_user_info();
  void set_allocated_user_info(::trpc::app::AppUserInfo* user_info);
  private:
  const ::trpc::app::AppUserInfo& _internal_user_info() const;
  ::trpc::app::AppUserInfo* _internal_mutable_user_info();
  public:
  void unsafe_arena_set_allocated_user_info(
      ::trpc::app::AppUserInfo* user_info);
  ::trpc::app::AppUserInfo* unsafe_arena_release_user_info();

  // @@protoc_insertion_point(class_scope:trpc.app.AppUserRegisterReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr public_key_;
  ::trpc::app::AppUserInfo* user_info_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_app_5fuser_5fitg_5fserver_2eproto;
};
// -------------------------------------------------------------------

class AppUserRegisterRsp PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:trpc.app.AppUserRegisterRsp) */ {
 public:
  inline AppUserRegisterRsp() : AppUserRegisterRsp(nullptr) {}
  virtual ~AppUserRegisterRsp();
  explicit constexpr AppUserRegisterRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppUserRegisterRsp(const AppUserRegisterRsp& from);
  AppUserRegisterRsp(AppUserRegisterRsp&& from) noexcept
    : AppUserRegisterRsp() {
    *this = ::std::move(from);
  }

  inline AppUserRegisterRsp& operator=(const AppUserRegisterRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppUserRegisterRsp& operator=(AppUserRegisterRsp&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AppUserRegisterRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppUserRegisterRsp* internal_default_instance() {
    return reinterpret_cast<const AppUserRegisterRsp*>(
               &_AppUserRegisterRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AppUserRegisterRsp& a, AppUserRegisterRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(AppUserRegisterRsp* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppUserRegisterRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AppUserRegisterRsp* New() const final {
    return CreateMaybeMessage<AppUserRegisterRsp>(nullptr);
  }

  AppUserRegisterRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AppUserRegisterRsp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AppUserRegisterRsp& from);
  void MergeFrom(const AppUserRegisterRsp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppUserRegisterRsp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "trpc.app.AppUserRegisterRsp";
  }
  protected:
  explicit AppUserRegisterRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_app_5fuser_5fitg_5fserver_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAppidFieldNumber = 1,
    kUidFieldNumber = 2,
  };
  // string appid = 1;
  void clear_appid();
  const std::string& appid() const;
  void set_appid(const std::string& value);
  void set_appid(std::string&& value);
  void set_appid(const char* value);
  void set_appid(const char* value, size_t size);
  std::string* mutable_appid();
  std::string* release_appid();
  void set_allocated_appid(std::string* appid);
  private:
  const std::string& _internal_appid() const;
  void _internal_set_appid(const std::string& value);
  std::string* _internal_mutable_appid();
  public:

  // string uid = 2;
  void clear_uid();
  const std::string& uid() const;
  void set_uid(const std::string& value);
  void set_uid(std::string&& value);
  void set_uid(const char* value);
  void set_uid(const char* value, size_t size);
  std::string* mutable_uid();
  std::string* release_uid();
  void set_allocated_uid(std::string* uid);
  private:
  const std::string& _internal_uid() const;
  void _internal_set_uid(const std::string& value);
  std::string* _internal_mutable_uid();
  public:

  // @@protoc_insertion_point(class_scope:trpc.app.AppUserRegisterRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr appid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_app_5fuser_5fitg_5fserver_2eproto;
};
// -------------------------------------------------------------------

class AppUserQueryInfoReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:trpc.app.AppUserQueryInfoReq) */ {
 public:
  inline AppUserQueryInfoReq() : AppUserQueryInfoReq(nullptr) {}
  virtual ~AppUserQueryInfoReq();
  explicit constexpr AppUserQueryInfoReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppUserQueryInfoReq(const AppUserQueryInfoReq& from);
  AppUserQueryInfoReq(AppUserQueryInfoReq&& from) noexcept
    : AppUserQueryInfoReq() {
    *this = ::std::move(from);
  }

  inline AppUserQueryInfoReq& operator=(const AppUserQueryInfoReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppUserQueryInfoReq& operator=(AppUserQueryInfoReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AppUserQueryInfoReq& default_instance() {
    return *internal_default_instance();
  }
  enum ConditionValueCase {
    kUid = 2,
    kPhone = 3,
    CONDITION_VALUE_NOT_SET = 0,
  };

  static inline const AppUserQueryInfoReq* internal_default_instance() {
    return reinterpret_cast<const AppUserQueryInfoReq*>(
               &_AppUserQueryInfoReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(AppUserQueryInfoReq& a, AppUserQueryInfoReq& b) {
    a.Swap(&b);
  }
  inline void Swap(AppUserQueryInfoReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppUserQueryInfoReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AppUserQueryInfoReq* New() const final {
    return CreateMaybeMessage<AppUserQueryInfoReq>(nullptr);
  }

  AppUserQueryInfoReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AppUserQueryInfoReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AppUserQueryInfoReq& from);
  void MergeFrom(const AppUserQueryInfoReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppUserQueryInfoReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "trpc.app.AppUserQueryInfoReq";
  }
  protected:
  explicit AppUserQueryInfoReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_app_5fuser_5fitg_5fserver_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConditionTypeFieldNumber = 1,
    kUidFieldNumber = 2,
    kPhoneFieldNumber = 3,
  };
  // uint32 condition_type = 1;
  void clear_condition_type();
  ::PROTOBUF_NAMESPACE_ID::uint32 condition_type() const;
  void set_condition_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_condition_type() const;
  void _internal_set_condition_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // string uid = 2;
  bool has_uid() const;
  private:
  bool _internal_has_uid() const;
  public:
  void clear_uid();
  const std::string& uid() const;
  void set_uid(const std::string& value);
  void set_uid(std::string&& value);
  void set_uid(const char* value);
  void set_uid(const char* value, size_t size);
  std::string* mutable_uid();
  std::string* release_uid();
  void set_allocated_uid(std::string* uid);
  private:
  const std::string& _internal_uid() const;
  void _internal_set_uid(const std::string& value);
  std::string* _internal_mutable_uid();
  public:

  // string phone = 3;
  bool has_phone() const;
  private:
  bool _internal_has_phone() const;
  public:
  void clear_phone();
  const std::string& phone() const;
  void set_phone(const std::string& value);
  void set_phone(std::string&& value);
  void set_phone(const char* value);
  void set_phone(const char* value, size_t size);
  std::string* mutable_phone();
  std::string* release_phone();
  void set_allocated_phone(std::string* phone);
  private:
  const std::string& _internal_phone() const;
  void _internal_set_phone(const std::string& value);
  std::string* _internal_mutable_phone();
  public:

  void clear_condition_value();
  ConditionValueCase condition_value_case() const;
  // @@protoc_insertion_point(class_scope:trpc.app.AppUserQueryInfoReq)
 private:
  class _Internal;
  void set_has_uid();
  void set_has_phone();

  inline bool has_condition_value() const;
  inline void clear_has_condition_value();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 condition_type_;
  union ConditionValueUnion {
    constexpr ConditionValueUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr phone_;
  } condition_value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_app_5fuser_5fitg_5fserver_2eproto;
};
// -------------------------------------------------------------------

class AppUserQueryInfoRsp PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:trpc.app.AppUserQueryInfoRsp) */ {
 public:
  inline AppUserQueryInfoRsp() : AppUserQueryInfoRsp(nullptr) {}
  virtual ~AppUserQueryInfoRsp();
  explicit constexpr AppUserQueryInfoRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppUserQueryInfoRsp(const AppUserQueryInfoRsp& from);
  AppUserQueryInfoRsp(AppUserQueryInfoRsp&& from) noexcept
    : AppUserQueryInfoRsp() {
    *this = ::std::move(from);
  }

  inline AppUserQueryInfoRsp& operator=(const AppUserQueryInfoRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppUserQueryInfoRsp& operator=(AppUserQueryInfoRsp&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AppUserQueryInfoRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppUserQueryInfoRsp* internal_default_instance() {
    return reinterpret_cast<const AppUserQueryInfoRsp*>(
               &_AppUserQueryInfoRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(AppUserQueryInfoRsp& a, AppUserQueryInfoRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(AppUserQueryInfoRsp* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppUserQueryInfoRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AppUserQueryInfoRsp* New() const final {
    return CreateMaybeMessage<AppUserQueryInfoRsp>(nullptr);
  }

  AppUserQueryInfoRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AppUserQueryInfoRsp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AppUserQueryInfoRsp& from);
  void MergeFrom(const AppUserQueryInfoRsp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppUserQueryInfoRsp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "trpc.app.AppUserQueryInfoRsp";
  }
  protected:
  explicit AppUserQueryInfoRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_app_5fuser_5fitg_5fserver_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserInfoFieldNumber = 1,
  };
  // .trpc.app.AppUserInfo user_info = 1;
  bool has_user_info() const;
  private:
  bool _internal_has_user_info() const;
  public:
  void clear_user_info();
  const ::trpc::app::AppUserInfo& user_info() const;
  ::trpc::app::AppUserInfo* release_user_info();
  ::trpc::app::AppUserInfo* mutable_user_info();
  void set_allocated_user_info(::trpc::app::AppUserInfo* user_info);
  private:
  const ::trpc::app::AppUserInfo& _internal_user_info() const;
  ::trpc::app::AppUserInfo* _internal_mutable_user_info();
  public:
  void unsafe_arena_set_allocated_user_info(
      ::trpc::app::AppUserInfo* user_info);
  ::trpc::app::AppUserInfo* unsafe_arena_release_user_info();

  // @@protoc_insertion_point(class_scope:trpc.app.AppUserQueryInfoRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::trpc::app::AppUserInfo* user_info_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_app_5fuser_5fitg_5fserver_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AppUserInfo

// string appid = 1;
inline void AppUserInfo::clear_appid() {
  appid_.ClearToEmpty();
}
inline const std::string& AppUserInfo::appid() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppUserInfo.appid)
  return _internal_appid();
}
inline void AppUserInfo::set_appid(const std::string& value) {
  _internal_set_appid(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppUserInfo.appid)
}
inline std::string* AppUserInfo::mutable_appid() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppUserInfo.appid)
  return _internal_mutable_appid();
}
inline const std::string& AppUserInfo::_internal_appid() const {
  return appid_.Get();
}
inline void AppUserInfo::_internal_set_appid(const std::string& value) {
  
  appid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppUserInfo::set_appid(std::string&& value) {
  
  appid_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppUserInfo.appid)
}
inline void AppUserInfo::set_appid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  appid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppUserInfo.appid)
}
inline void AppUserInfo::set_appid(const char* value,
    size_t size) {
  
  appid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppUserInfo.appid)
}
inline std::string* AppUserInfo::_internal_mutable_appid() {
  
  return appid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppUserInfo::release_appid() {
  // @@protoc_insertion_point(field_release:trpc.app.AppUserInfo.appid)
  return appid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppUserInfo::set_allocated_appid(std::string* appid) {
  if (appid != nullptr) {
    
  } else {
    
  }
  appid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), appid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppUserInfo.appid)
}

// string phone = 2;
inline void AppUserInfo::clear_phone() {
  phone_.ClearToEmpty();
}
inline const std::string& AppUserInfo::phone() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppUserInfo.phone)
  return _internal_phone();
}
inline void AppUserInfo::set_phone(const std::string& value) {
  _internal_set_phone(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppUserInfo.phone)
}
inline std::string* AppUserInfo::mutable_phone() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppUserInfo.phone)
  return _internal_mutable_phone();
}
inline const std::string& AppUserInfo::_internal_phone() const {
  return phone_.Get();
}
inline void AppUserInfo::_internal_set_phone(const std::string& value) {
  
  phone_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppUserInfo::set_phone(std::string&& value) {
  
  phone_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppUserInfo.phone)
}
inline void AppUserInfo::set_phone(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  phone_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppUserInfo.phone)
}
inline void AppUserInfo::set_phone(const char* value,
    size_t size) {
  
  phone_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppUserInfo.phone)
}
inline std::string* AppUserInfo::_internal_mutable_phone() {
  
  return phone_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppUserInfo::release_phone() {
  // @@protoc_insertion_point(field_release:trpc.app.AppUserInfo.phone)
  return phone_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppUserInfo::set_allocated_phone(std::string* phone) {
  if (phone != nullptr) {
    
  } else {
    
  }
  phone_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), phone,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppUserInfo.phone)
}

// string user_name = 3;
inline void AppUserInfo::clear_user_name() {
  user_name_.ClearToEmpty();
}
inline const std::string& AppUserInfo::user_name() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppUserInfo.user_name)
  return _internal_user_name();
}
inline void AppUserInfo::set_user_name(const std::string& value) {
  _internal_set_user_name(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppUserInfo.user_name)
}
inline std::string* AppUserInfo::mutable_user_name() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppUserInfo.user_name)
  return _internal_mutable_user_name();
}
inline const std::string& AppUserInfo::_internal_user_name() const {
  return user_name_.Get();
}
inline void AppUserInfo::_internal_set_user_name(const std::string& value) {
  
  user_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppUserInfo::set_user_name(std::string&& value) {
  
  user_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppUserInfo.user_name)
}
inline void AppUserInfo::set_user_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  user_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppUserInfo.user_name)
}
inline void AppUserInfo::set_user_name(const char* value,
    size_t size) {
  
  user_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppUserInfo.user_name)
}
inline std::string* AppUserInfo::_internal_mutable_user_name() {
  
  return user_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppUserInfo::release_user_name() {
  // @@protoc_insertion_point(field_release:trpc.app.AppUserInfo.user_name)
  return user_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppUserInfo::set_allocated_user_name(std::string* user_name) {
  if (user_name != nullptr) {
    
  } else {
    
  }
  user_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppUserInfo.user_name)
}

// string register_time = 4;
inline void AppUserInfo::clear_register_time() {
  register_time_.ClearToEmpty();
}
inline const std::string& AppUserInfo::register_time() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppUserInfo.register_time)
  return _internal_register_time();
}
inline void AppUserInfo::set_register_time(const std::string& value) {
  _internal_set_register_time(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppUserInfo.register_time)
}
inline std::string* AppUserInfo::mutable_register_time() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppUserInfo.register_time)
  return _internal_mutable_register_time();
}
inline const std::string& AppUserInfo::_internal_register_time() const {
  return register_time_.Get();
}
inline void AppUserInfo::_internal_set_register_time(const std::string& value) {
  
  register_time_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppUserInfo::set_register_time(std::string&& value) {
  
  register_time_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppUserInfo.register_time)
}
inline void AppUserInfo::set_register_time(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  register_time_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppUserInfo.register_time)
}
inline void AppUserInfo::set_register_time(const char* value,
    size_t size) {
  
  register_time_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppUserInfo.register_time)
}
inline std::string* AppUserInfo::_internal_mutable_register_time() {
  
  return register_time_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppUserInfo::release_register_time() {
  // @@protoc_insertion_point(field_release:trpc.app.AppUserInfo.register_time)
  return register_time_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppUserInfo::set_allocated_register_time(std::string* register_time) {
  if (register_time != nullptr) {
    
  } else {
    
  }
  register_time_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), register_time,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppUserInfo.register_time)
}

// string password = 5;
inline bool AppUserInfo::_internal_has_password() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool AppUserInfo::has_password() const {
  return _internal_has_password();
}
inline void AppUserInfo::clear_password() {
  password_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& AppUserInfo::password() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppUserInfo.password)
  return _internal_password();
}
inline void AppUserInfo::set_password(const std::string& value) {
  _internal_set_password(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppUserInfo.password)
}
inline std::string* AppUserInfo::mutable_password() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppUserInfo.password)
  return _internal_mutable_password();
}
inline const std::string& AppUserInfo::_internal_password() const {
  return password_.Get();
}
inline void AppUserInfo::_internal_set_password(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppUserInfo::set_password(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  password_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppUserInfo.password)
}
inline void AppUserInfo::set_password(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppUserInfo.password)
}
inline void AppUserInfo::set_password(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppUserInfo.password)
}
inline std::string* AppUserInfo::_internal_mutable_password() {
  _has_bits_[0] |= 0x00000001u;
  return password_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppUserInfo::release_password() {
  // @@protoc_insertion_point(field_release:trpc.app.AppUserInfo.password)
  if (!_internal_has_password()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return password_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppUserInfo::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  password_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppUserInfo.password)
}

// string icon_url = 6;
inline bool AppUserInfo::_internal_has_icon_url() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool AppUserInfo::has_icon_url() const {
  return _internal_has_icon_url();
}
inline void AppUserInfo::clear_icon_url() {
  icon_url_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& AppUserInfo::icon_url() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppUserInfo.icon_url)
  return _internal_icon_url();
}
inline void AppUserInfo::set_icon_url(const std::string& value) {
  _internal_set_icon_url(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppUserInfo.icon_url)
}
inline std::string* AppUserInfo::mutable_icon_url() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppUserInfo.icon_url)
  return _internal_mutable_icon_url();
}
inline const std::string& AppUserInfo::_internal_icon_url() const {
  return icon_url_.Get();
}
inline void AppUserInfo::_internal_set_icon_url(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  icon_url_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppUserInfo::set_icon_url(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  icon_url_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppUserInfo.icon_url)
}
inline void AppUserInfo::set_icon_url(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  icon_url_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppUserInfo.icon_url)
}
inline void AppUserInfo::set_icon_url(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  icon_url_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppUserInfo.icon_url)
}
inline std::string* AppUserInfo::_internal_mutable_icon_url() {
  _has_bits_[0] |= 0x00000002u;
  return icon_url_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppUserInfo::release_icon_url() {
  // @@protoc_insertion_point(field_release:trpc.app.AppUserInfo.icon_url)
  if (!_internal_has_icon_url()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return icon_url_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppUserInfo::set_allocated_icon_url(std::string* icon_url) {
  if (icon_url != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  icon_url_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), icon_url,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppUserInfo.icon_url)
}

// -------------------------------------------------------------------

// AppUserRegisterReq

// .trpc.app.AppUserInfo user_info = 1;
inline bool AppUserRegisterReq::_internal_has_user_info() const {
  return this != internal_default_instance() && user_info_ != nullptr;
}
inline bool AppUserRegisterReq::has_user_info() const {
  return _internal_has_user_info();
}
inline void AppUserRegisterReq::clear_user_info() {
  if (GetArena() == nullptr && user_info_ != nullptr) {
    delete user_info_;
  }
  user_info_ = nullptr;
}
inline const ::trpc::app::AppUserInfo& AppUserRegisterReq::_internal_user_info() const {
  const ::trpc::app::AppUserInfo* p = user_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::trpc::app::AppUserInfo&>(
      ::trpc::app::_AppUserInfo_default_instance_);
}
inline const ::trpc::app::AppUserInfo& AppUserRegisterReq::user_info() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppUserRegisterReq.user_info)
  return _internal_user_info();
}
inline void AppUserRegisterReq::unsafe_arena_set_allocated_user_info(
    ::trpc::app::AppUserInfo* user_info) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(user_info_);
  }
  user_info_ = user_info;
  if (user_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:trpc.app.AppUserRegisterReq.user_info)
}
inline ::trpc::app::AppUserInfo* AppUserRegisterReq::release_user_info() {
  
  ::trpc::app::AppUserInfo* temp = user_info_;
  user_info_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::trpc::app::AppUserInfo* AppUserRegisterReq::unsafe_arena_release_user_info() {
  // @@protoc_insertion_point(field_release:trpc.app.AppUserRegisterReq.user_info)
  
  ::trpc::app::AppUserInfo* temp = user_info_;
  user_info_ = nullptr;
  return temp;
}
inline ::trpc::app::AppUserInfo* AppUserRegisterReq::_internal_mutable_user_info() {
  
  if (user_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::trpc::app::AppUserInfo>(GetArena());
    user_info_ = p;
  }
  return user_info_;
}
inline ::trpc::app::AppUserInfo* AppUserRegisterReq::mutable_user_info() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppUserRegisterReq.user_info)
  return _internal_mutable_user_info();
}
inline void AppUserRegisterReq::set_allocated_user_info(::trpc::app::AppUserInfo* user_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete user_info_;
  }
  if (user_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(user_info);
    if (message_arena != submessage_arena) {
      user_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, user_info, submessage_arena);
    }
    
  } else {
    
  }
  user_info_ = user_info;
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppUserRegisterReq.user_info)
}

// string public_key = 2;
inline void AppUserRegisterReq::clear_public_key() {
  public_key_.ClearToEmpty();
}
inline const std::string& AppUserRegisterReq::public_key() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppUserRegisterReq.public_key)
  return _internal_public_key();
}
inline void AppUserRegisterReq::set_public_key(const std::string& value) {
  _internal_set_public_key(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppUserRegisterReq.public_key)
}
inline std::string* AppUserRegisterReq::mutable_public_key() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppUserRegisterReq.public_key)
  return _internal_mutable_public_key();
}
inline const std::string& AppUserRegisterReq::_internal_public_key() const {
  return public_key_.Get();
}
inline void AppUserRegisterReq::_internal_set_public_key(const std::string& value) {
  
  public_key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppUserRegisterReq::set_public_key(std::string&& value) {
  
  public_key_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppUserRegisterReq.public_key)
}
inline void AppUserRegisterReq::set_public_key(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  public_key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppUserRegisterReq.public_key)
}
inline void AppUserRegisterReq::set_public_key(const char* value,
    size_t size) {
  
  public_key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppUserRegisterReq.public_key)
}
inline std::string* AppUserRegisterReq::_internal_mutable_public_key() {
  
  return public_key_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppUserRegisterReq::release_public_key() {
  // @@protoc_insertion_point(field_release:trpc.app.AppUserRegisterReq.public_key)
  return public_key_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppUserRegisterReq::set_allocated_public_key(std::string* public_key) {
  if (public_key != nullptr) {
    
  } else {
    
  }
  public_key_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), public_key,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppUserRegisterReq.public_key)
}

// -------------------------------------------------------------------

// AppUserRegisterRsp

// string appid = 1;
inline void AppUserRegisterRsp::clear_appid() {
  appid_.ClearToEmpty();
}
inline const std::string& AppUserRegisterRsp::appid() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppUserRegisterRsp.appid)
  return _internal_appid();
}
inline void AppUserRegisterRsp::set_appid(const std::string& value) {
  _internal_set_appid(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppUserRegisterRsp.appid)
}
inline std::string* AppUserRegisterRsp::mutable_appid() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppUserRegisterRsp.appid)
  return _internal_mutable_appid();
}
inline const std::string& AppUserRegisterRsp::_internal_appid() const {
  return appid_.Get();
}
inline void AppUserRegisterRsp::_internal_set_appid(const std::string& value) {
  
  appid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppUserRegisterRsp::set_appid(std::string&& value) {
  
  appid_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppUserRegisterRsp.appid)
}
inline void AppUserRegisterRsp::set_appid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  appid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppUserRegisterRsp.appid)
}
inline void AppUserRegisterRsp::set_appid(const char* value,
    size_t size) {
  
  appid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppUserRegisterRsp.appid)
}
inline std::string* AppUserRegisterRsp::_internal_mutable_appid() {
  
  return appid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppUserRegisterRsp::release_appid() {
  // @@protoc_insertion_point(field_release:trpc.app.AppUserRegisterRsp.appid)
  return appid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppUserRegisterRsp::set_allocated_appid(std::string* appid) {
  if (appid != nullptr) {
    
  } else {
    
  }
  appid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), appid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppUserRegisterRsp.appid)
}

// string uid = 2;
inline void AppUserRegisterRsp::clear_uid() {
  uid_.ClearToEmpty();
}
inline const std::string& AppUserRegisterRsp::uid() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppUserRegisterRsp.uid)
  return _internal_uid();
}
inline void AppUserRegisterRsp::set_uid(const std::string& value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppUserRegisterRsp.uid)
}
inline std::string* AppUserRegisterRsp::mutable_uid() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppUserRegisterRsp.uid)
  return _internal_mutable_uid();
}
inline const std::string& AppUserRegisterRsp::_internal_uid() const {
  return uid_.Get();
}
inline void AppUserRegisterRsp::_internal_set_uid(const std::string& value) {
  
  uid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppUserRegisterRsp::set_uid(std::string&& value) {
  
  uid_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppUserRegisterRsp.uid)
}
inline void AppUserRegisterRsp::set_uid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  uid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppUserRegisterRsp.uid)
}
inline void AppUserRegisterRsp::set_uid(const char* value,
    size_t size) {
  
  uid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppUserRegisterRsp.uid)
}
inline std::string* AppUserRegisterRsp::_internal_mutable_uid() {
  
  return uid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppUserRegisterRsp::release_uid() {
  // @@protoc_insertion_point(field_release:trpc.app.AppUserRegisterRsp.uid)
  return uid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppUserRegisterRsp::set_allocated_uid(std::string* uid) {
  if (uid != nullptr) {
    
  } else {
    
  }
  uid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), uid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppUserRegisterRsp.uid)
}

// -------------------------------------------------------------------

// AppUserQueryInfoReq

// uint32 condition_type = 1;
inline void AppUserQueryInfoReq::clear_condition_type() {
  condition_type_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AppUserQueryInfoReq::_internal_condition_type() const {
  return condition_type_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AppUserQueryInfoReq::condition_type() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppUserQueryInfoReq.condition_type)
  return _internal_condition_type();
}
inline void AppUserQueryInfoReq::_internal_set_condition_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  condition_type_ = value;
}
inline void AppUserQueryInfoReq::set_condition_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_condition_type(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppUserQueryInfoReq.condition_type)
}

// string uid = 2;
inline bool AppUserQueryInfoReq::_internal_has_uid() const {
  return condition_value_case() == kUid;
}
inline bool AppUserQueryInfoReq::has_uid() const {
  return _internal_has_uid();
}
inline void AppUserQueryInfoReq::set_has_uid() {
  _oneof_case_[0] = kUid;
}
inline void AppUserQueryInfoReq::clear_uid() {
  if (_internal_has_uid()) {
    condition_value_.uid_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
    clear_has_condition_value();
  }
}
inline const std::string& AppUserQueryInfoReq::uid() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppUserQueryInfoReq.uid)
  return _internal_uid();
}
inline void AppUserQueryInfoReq::set_uid(const std::string& value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppUserQueryInfoReq.uid)
}
inline std::string* AppUserQueryInfoReq::mutable_uid() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppUserQueryInfoReq.uid)
  return _internal_mutable_uid();
}
inline const std::string& AppUserQueryInfoReq::_internal_uid() const {
  if (_internal_has_uid()) {
    return condition_value_.uid_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void AppUserQueryInfoReq::_internal_set_uid(const std::string& value) {
  if (!_internal_has_uid()) {
    clear_condition_value();
    set_has_uid();
    condition_value_.uid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  condition_value_.uid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppUserQueryInfoReq::set_uid(std::string&& value) {
  // @@protoc_insertion_point(field_set:trpc.app.AppUserQueryInfoReq.uid)
  if (!_internal_has_uid()) {
    clear_condition_value();
    set_has_uid();
    condition_value_.uid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  condition_value_.uid_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppUserQueryInfoReq.uid)
}
inline void AppUserQueryInfoReq::set_uid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  if (!_internal_has_uid()) {
    clear_condition_value();
    set_has_uid();
    condition_value_.uid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  condition_value_.uid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{},
      ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppUserQueryInfoReq.uid)
}
inline void AppUserQueryInfoReq::set_uid(const char* value,
                             size_t size) {
  if (!_internal_has_uid()) {
    clear_condition_value();
    set_has_uid();
    condition_value_.uid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  condition_value_.uid_.Set(
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size),
      GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppUserQueryInfoReq.uid)
}
inline std::string* AppUserQueryInfoReq::_internal_mutable_uid() {
  if (!_internal_has_uid()) {
    clear_condition_value();
    set_has_uid();
    condition_value_.uid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  return condition_value_.uid_.Mutable(
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppUserQueryInfoReq::release_uid() {
  // @@protoc_insertion_point(field_release:trpc.app.AppUserQueryInfoReq.uid)
  if (_internal_has_uid()) {
    clear_has_condition_value();
    return condition_value_.uid_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  } else {
    return nullptr;
  }
}
inline void AppUserQueryInfoReq::set_allocated_uid(std::string* uid) {
  if (has_condition_value()) {
    clear_condition_value();
  }
  if (uid != nullptr) {
    set_has_uid();
    condition_value_.uid_.UnsafeSetDefault(uid);
    ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena();
    if (arena != nullptr) {
      arena->Own(uid);
    }
  }
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppUserQueryInfoReq.uid)
}

// string phone = 3;
inline bool AppUserQueryInfoReq::_internal_has_phone() const {
  return condition_value_case() == kPhone;
}
inline bool AppUserQueryInfoReq::has_phone() const {
  return _internal_has_phone();
}
inline void AppUserQueryInfoReq::set_has_phone() {
  _oneof_case_[0] = kPhone;
}
inline void AppUserQueryInfoReq::clear_phone() {
  if (_internal_has_phone()) {
    condition_value_.phone_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
    clear_has_condition_value();
  }
}
inline const std::string& AppUserQueryInfoReq::phone() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppUserQueryInfoReq.phone)
  return _internal_phone();
}
inline void AppUserQueryInfoReq::set_phone(const std::string& value) {
  _internal_set_phone(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppUserQueryInfoReq.phone)
}
inline std::string* AppUserQueryInfoReq::mutable_phone() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppUserQueryInfoReq.phone)
  return _internal_mutable_phone();
}
inline const std::string& AppUserQueryInfoReq::_internal_phone() const {
  if (_internal_has_phone()) {
    return condition_value_.phone_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void AppUserQueryInfoReq::_internal_set_phone(const std::string& value) {
  if (!_internal_has_phone()) {
    clear_condition_value();
    set_has_phone();
    condition_value_.phone_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  condition_value_.phone_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppUserQueryInfoReq::set_phone(std::string&& value) {
  // @@protoc_insertion_point(field_set:trpc.app.AppUserQueryInfoReq.phone)
  if (!_internal_has_phone()) {
    clear_condition_value();
    set_has_phone();
    condition_value_.phone_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  condition_value_.phone_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppUserQueryInfoReq.phone)
}
inline void AppUserQueryInfoReq::set_phone(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  if (!_internal_has_phone()) {
    clear_condition_value();
    set_has_phone();
    condition_value_.phone_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  condition_value_.phone_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{},
      ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppUserQueryInfoReq.phone)
}
inline void AppUserQueryInfoReq::set_phone(const char* value,
                             size_t size) {
  if (!_internal_has_phone()) {
    clear_condition_value();
    set_has_phone();
    condition_value_.phone_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  condition_value_.phone_.Set(
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size),
      GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppUserQueryInfoReq.phone)
}
inline std::string* AppUserQueryInfoReq::_internal_mutable_phone() {
  if (!_internal_has_phone()) {
    clear_condition_value();
    set_has_phone();
    condition_value_.phone_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  return condition_value_.phone_.Mutable(
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppUserQueryInfoReq::release_phone() {
  // @@protoc_insertion_point(field_release:trpc.app.AppUserQueryInfoReq.phone)
  if (_internal_has_phone()) {
    clear_has_condition_value();
    return condition_value_.phone_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  } else {
    return nullptr;
  }
}
inline void AppUserQueryInfoReq::set_allocated_phone(std::string* phone) {
  if (has_condition_value()) {
    clear_condition_value();
  }
  if (phone != nullptr) {
    set_has_phone();
    condition_value_.phone_.UnsafeSetDefault(phone);
    ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena();
    if (arena != nullptr) {
      arena->Own(phone);
    }
  }
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppUserQueryInfoReq.phone)
}

inline bool AppUserQueryInfoReq::has_condition_value() const {
  return condition_value_case() != CONDITION_VALUE_NOT_SET;
}
inline void AppUserQueryInfoReq::clear_has_condition_value() {
  _oneof_case_[0] = CONDITION_VALUE_NOT_SET;
}
inline AppUserQueryInfoReq::ConditionValueCase AppUserQueryInfoReq::condition_value_case() const {
  return AppUserQueryInfoReq::ConditionValueCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// AppUserQueryInfoRsp

// .trpc.app.AppUserInfo user_info = 1;
inline bool AppUserQueryInfoRsp::_internal_has_user_info() const {
  return this != internal_default_instance() && user_info_ != nullptr;
}
inline bool AppUserQueryInfoRsp::has_user_info() const {
  return _internal_has_user_info();
}
inline void AppUserQueryInfoRsp::clear_user_info() {
  if (GetArena() == nullptr && user_info_ != nullptr) {
    delete user_info_;
  }
  user_info_ = nullptr;
}
inline const ::trpc::app::AppUserInfo& AppUserQueryInfoRsp::_internal_user_info() const {
  const ::trpc::app::AppUserInfo* p = user_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::trpc::app::AppUserInfo&>(
      ::trpc::app::_AppUserInfo_default_instance_);
}
inline const ::trpc::app::AppUserInfo& AppUserQueryInfoRsp::user_info() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppUserQueryInfoRsp.user_info)
  return _internal_user_info();
}
inline void AppUserQueryInfoRsp::unsafe_arena_set_allocated_user_info(
    ::trpc::app::AppUserInfo* user_info) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(user_info_);
  }
  user_info_ = user_info;
  if (user_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:trpc.app.AppUserQueryInfoRsp.user_info)
}
inline ::trpc::app::AppUserInfo* AppUserQueryInfoRsp::release_user_info() {
  
  ::trpc::app::AppUserInfo* temp = user_info_;
  user_info_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::trpc::app::AppUserInfo* AppUserQueryInfoRsp::unsafe_arena_release_user_info() {
  // @@protoc_insertion_point(field_release:trpc.app.AppUserQueryInfoRsp.user_info)
  
  ::trpc::app::AppUserInfo* temp = user_info_;
  user_info_ = nullptr;
  return temp;
}
inline ::trpc::app::AppUserInfo* AppUserQueryInfoRsp::_internal_mutable_user_info() {
  
  if (user_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::trpc::app::AppUserInfo>(GetArena());
    user_info_ = p;
  }
  return user_info_;
}
inline ::trpc::app::AppUserInfo* AppUserQueryInfoRsp::mutable_user_info() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppUserQueryInfoRsp.user_info)
  return _internal_mutable_user_info();
}
inline void AppUserQueryInfoRsp::set_allocated_user_info(::trpc::app::AppUserInfo* user_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete user_info_;
  }
  if (user_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(user_info);
    if (message_arena != submessage_arena) {
      user_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, user_info, submessage_arena);
    }
    
  } else {
    
  }
  user_info_ = user_info;
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppUserQueryInfoRsp.user_info)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace app
}  // namespace trpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_app_5fuser_5fitg_5fserver_2eproto
