//
// This file was generated by trpc_cpp_plugin which is a self-defined pb compiler plugin, do not edit it!!!
// All rights reserved by Tencent Corporation
//

#pragma once

#include "app_busi_itg_server.pb.h"

#include "trpc/client/rpc_service_proxy.h"
#include "trpc/server/rpc_service_impl.h"

namespace trpc {
namespace app {

class AppBusiItgService : public ::trpc::RpcServiceImpl {
 public:
  AppBusiItgService();

  virtual ::trpc::Status AppBusiBirthdateConvertHandler(::trpc::ServerContextPtr context, const ::trpc::app::AppBusiBirthdateConvertReq* request, ::trpc::app::AppBusiBirthdateConvertRsp* response);
};

class AsyncAppBusiItgService : public ::trpc::AsyncRpcServiceImpl {
 public:
  AsyncAppBusiItgService();
  
  virtual ::trpc::Future<::trpc::app::AppBusiBirthdateConvertRsp> AppBusiBirthdateConvertHandler(const ::trpc::ServerContextPtr& context, const ::trpc::app::AppBusiBirthdateConvertReq* request);
};

class AppBusiItgServiceServiceProxy : public ::trpc::RpcServiceProxy {
 public:
  virtual ::trpc::Status AppBusiBirthdateConvertHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppBusiBirthdateConvertReq& request, ::trpc::app::AppBusiBirthdateConvertRsp* response);
  virtual ::trpc::Future<::trpc::app::AppBusiBirthdateConvertRsp> AsyncAppBusiBirthdateConvertHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppBusiBirthdateConvertReq& request);
  // oneway, only send
  virtual ::trpc::Status AppBusiBirthdateConvertHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppBusiBirthdateConvertReq& request);
};

class AsyncAppBusiItgServiceServiceProxy : public ::trpc::RpcServiceProxy {
 public:
  ::trpc::Future<::trpc::app::AppBusiBirthdateConvertRsp> AppBusiBirthdateConvertHandler(const ::trpc::ClientContextPtr& context, const ::trpc::app::AppBusiBirthdateConvertReq& request);
  // TODO: one-way
};

} // end namespace app
} // end namespace trpc