// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_busi_itg_server.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_app_5fbusi_5fitg_5fserver_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_app_5fbusi_5fitg_5fserver_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_app_5fbusi_5fitg_5fserver_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_app_5fbusi_5fitg_5fserver_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_app_5fbusi_5fitg_5fserver_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_app_5fbusi_5fitg_5fserver_2eproto_metadata_getter(int index);
namespace trpc {
namespace app {
class AppBusiBirthdateConvertReq;
struct AppBusiBirthdateConvertReqDefaultTypeInternal;
extern AppBusiBirthdateConvertReqDefaultTypeInternal _AppBusiBirthdateConvertReq_default_instance_;
class AppBusiBirthdateConvertRsp;
struct AppBusiBirthdateConvertRspDefaultTypeInternal;
extern AppBusiBirthdateConvertRspDefaultTypeInternal _AppBusiBirthdateConvertRsp_default_instance_;
}  // namespace app
}  // namespace trpc
PROTOBUF_NAMESPACE_OPEN
template<> ::trpc::app::AppBusiBirthdateConvertReq* Arena::CreateMaybeMessage<::trpc::app::AppBusiBirthdateConvertReq>(Arena*);
template<> ::trpc::app::AppBusiBirthdateConvertRsp* Arena::CreateMaybeMessage<::trpc::app::AppBusiBirthdateConvertRsp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace trpc {
namespace app {

// ===================================================================

class AppBusiBirthdateConvertReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:trpc.app.AppBusiBirthdateConvertReq) */ {
 public:
  inline AppBusiBirthdateConvertReq() : AppBusiBirthdateConvertReq(nullptr) {}
  virtual ~AppBusiBirthdateConvertReq();
  explicit constexpr AppBusiBirthdateConvertReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppBusiBirthdateConvertReq(const AppBusiBirthdateConvertReq& from);
  AppBusiBirthdateConvertReq(AppBusiBirthdateConvertReq&& from) noexcept
    : AppBusiBirthdateConvertReq() {
    *this = ::std::move(from);
  }

  inline AppBusiBirthdateConvertReq& operator=(const AppBusiBirthdateConvertReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppBusiBirthdateConvertReq& operator=(AppBusiBirthdateConvertReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AppBusiBirthdateConvertReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppBusiBirthdateConvertReq* internal_default_instance() {
    return reinterpret_cast<const AppBusiBirthdateConvertReq*>(
               &_AppBusiBirthdateConvertReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AppBusiBirthdateConvertReq& a, AppBusiBirthdateConvertReq& b) {
    a.Swap(&b);
  }
  inline void Swap(AppBusiBirthdateConvertReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppBusiBirthdateConvertReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AppBusiBirthdateConvertReq* New() const final {
    return CreateMaybeMessage<AppBusiBirthdateConvertReq>(nullptr);
  }

  AppBusiBirthdateConvertReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AppBusiBirthdateConvertReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AppBusiBirthdateConvertReq& from);
  void MergeFrom(const AppBusiBirthdateConvertReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppBusiBirthdateConvertReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "trpc.app.AppBusiBirthdateConvertReq";
  }
  protected:
  explicit AppBusiBirthdateConvertReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_app_5fbusi_5fitg_5fserver_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBirthdateFieldNumber = 1,
  };
  // string birthdate = 1;
  void clear_birthdate();
  const std::string& birthdate() const;
  void set_birthdate(const std::string& value);
  void set_birthdate(std::string&& value);
  void set_birthdate(const char* value);
  void set_birthdate(const char* value, size_t size);
  std::string* mutable_birthdate();
  std::string* release_birthdate();
  void set_allocated_birthdate(std::string* birthdate);
  private:
  const std::string& _internal_birthdate() const;
  void _internal_set_birthdate(const std::string& value);
  std::string* _internal_mutable_birthdate();
  public:

  // @@protoc_insertion_point(class_scope:trpc.app.AppBusiBirthdateConvertReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr birthdate_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_app_5fbusi_5fitg_5fserver_2eproto;
};
// -------------------------------------------------------------------

class AppBusiBirthdateConvertRsp PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:trpc.app.AppBusiBirthdateConvertRsp) */ {
 public:
  inline AppBusiBirthdateConvertRsp() : AppBusiBirthdateConvertRsp(nullptr) {}
  virtual ~AppBusiBirthdateConvertRsp();
  explicit constexpr AppBusiBirthdateConvertRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppBusiBirthdateConvertRsp(const AppBusiBirthdateConvertRsp& from);
  AppBusiBirthdateConvertRsp(AppBusiBirthdateConvertRsp&& from) noexcept
    : AppBusiBirthdateConvertRsp() {
    *this = ::std::move(from);
  }

  inline AppBusiBirthdateConvertRsp& operator=(const AppBusiBirthdateConvertRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppBusiBirthdateConvertRsp& operator=(AppBusiBirthdateConvertRsp&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AppBusiBirthdateConvertRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppBusiBirthdateConvertRsp* internal_default_instance() {
    return reinterpret_cast<const AppBusiBirthdateConvertRsp*>(
               &_AppBusiBirthdateConvertRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AppBusiBirthdateConvertRsp& a, AppBusiBirthdateConvertRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(AppBusiBirthdateConvertRsp* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppBusiBirthdateConvertRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AppBusiBirthdateConvertRsp* New() const final {
    return CreateMaybeMessage<AppBusiBirthdateConvertRsp>(nullptr);
  }

  AppBusiBirthdateConvertRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AppBusiBirthdateConvertRsp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AppBusiBirthdateConvertRsp& from);
  void MergeFrom(const AppBusiBirthdateConvertRsp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppBusiBirthdateConvertRsp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "trpc.app.AppBusiBirthdateConvertRsp";
  }
  protected:
  explicit AppBusiBirthdateConvertRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_app_5fbusi_5fitg_5fserver_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBirthdateFieldNumber = 1,
    kGzYearFieldNumber = 2,
    kGzMonthFieldNumber = 3,
    kGzDayFieldNumber = 4,
    kGzHourFieldNumber = 5,
  };
  // string birthdate = 1;
  void clear_birthdate();
  const std::string& birthdate() const;
  void set_birthdate(const std::string& value);
  void set_birthdate(std::string&& value);
  void set_birthdate(const char* value);
  void set_birthdate(const char* value, size_t size);
  std::string* mutable_birthdate();
  std::string* release_birthdate();
  void set_allocated_birthdate(std::string* birthdate);
  private:
  const std::string& _internal_birthdate() const;
  void _internal_set_birthdate(const std::string& value);
  std::string* _internal_mutable_birthdate();
  public:

  // string gz_year = 2;
  void clear_gz_year();
  const std::string& gz_year() const;
  void set_gz_year(const std::string& value);
  void set_gz_year(std::string&& value);
  void set_gz_year(const char* value);
  void set_gz_year(const char* value, size_t size);
  std::string* mutable_gz_year();
  std::string* release_gz_year();
  void set_allocated_gz_year(std::string* gz_year);
  private:
  const std::string& _internal_gz_year() const;
  void _internal_set_gz_year(const std::string& value);
  std::string* _internal_mutable_gz_year();
  public:

  // string gz_month = 3;
  void clear_gz_month();
  const std::string& gz_month() const;
  void set_gz_month(const std::string& value);
  void set_gz_month(std::string&& value);
  void set_gz_month(const char* value);
  void set_gz_month(const char* value, size_t size);
  std::string* mutable_gz_month();
  std::string* release_gz_month();
  void set_allocated_gz_month(std::string* gz_month);
  private:
  const std::string& _internal_gz_month() const;
  void _internal_set_gz_month(const std::string& value);
  std::string* _internal_mutable_gz_month();
  public:

  // string gz_day = 4;
  void clear_gz_day();
  const std::string& gz_day() const;
  void set_gz_day(const std::string& value);
  void set_gz_day(std::string&& value);
  void set_gz_day(const char* value);
  void set_gz_day(const char* value, size_t size);
  std::string* mutable_gz_day();
  std::string* release_gz_day();
  void set_allocated_gz_day(std::string* gz_day);
  private:
  const std::string& _internal_gz_day() const;
  void _internal_set_gz_day(const std::string& value);
  std::string* _internal_mutable_gz_day();
  public:

  // string gz_hour = 5;
  void clear_gz_hour();
  const std::string& gz_hour() const;
  void set_gz_hour(const std::string& value);
  void set_gz_hour(std::string&& value);
  void set_gz_hour(const char* value);
  void set_gz_hour(const char* value, size_t size);
  std::string* mutable_gz_hour();
  std::string* release_gz_hour();
  void set_allocated_gz_hour(std::string* gz_hour);
  private:
  const std::string& _internal_gz_hour() const;
  void _internal_set_gz_hour(const std::string& value);
  std::string* _internal_mutable_gz_hour();
  public:

  // @@protoc_insertion_point(class_scope:trpc.app.AppBusiBirthdateConvertRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr birthdate_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr gz_year_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr gz_month_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr gz_day_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr gz_hour_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_app_5fbusi_5fitg_5fserver_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AppBusiBirthdateConvertReq

// string birthdate = 1;
inline void AppBusiBirthdateConvertReq::clear_birthdate() {
  birthdate_.ClearToEmpty();
}
inline const std::string& AppBusiBirthdateConvertReq::birthdate() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBirthdateConvertReq.birthdate)
  return _internal_birthdate();
}
inline void AppBusiBirthdateConvertReq::set_birthdate(const std::string& value) {
  _internal_set_birthdate(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBirthdateConvertReq.birthdate)
}
inline std::string* AppBusiBirthdateConvertReq::mutable_birthdate() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppBusiBirthdateConvertReq.birthdate)
  return _internal_mutable_birthdate();
}
inline const std::string& AppBusiBirthdateConvertReq::_internal_birthdate() const {
  return birthdate_.Get();
}
inline void AppBusiBirthdateConvertReq::_internal_set_birthdate(const std::string& value) {
  
  birthdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppBusiBirthdateConvertReq::set_birthdate(std::string&& value) {
  
  birthdate_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppBusiBirthdateConvertReq.birthdate)
}
inline void AppBusiBirthdateConvertReq::set_birthdate(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  birthdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppBusiBirthdateConvertReq.birthdate)
}
inline void AppBusiBirthdateConvertReq::set_birthdate(const char* value,
    size_t size) {
  
  birthdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppBusiBirthdateConvertReq.birthdate)
}
inline std::string* AppBusiBirthdateConvertReq::_internal_mutable_birthdate() {
  
  return birthdate_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppBusiBirthdateConvertReq::release_birthdate() {
  // @@protoc_insertion_point(field_release:trpc.app.AppBusiBirthdateConvertReq.birthdate)
  return birthdate_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppBusiBirthdateConvertReq::set_allocated_birthdate(std::string* birthdate) {
  if (birthdate != nullptr) {
    
  } else {
    
  }
  birthdate_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), birthdate,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppBusiBirthdateConvertReq.birthdate)
}

// -------------------------------------------------------------------

// AppBusiBirthdateConvertRsp

// string birthdate = 1;
inline void AppBusiBirthdateConvertRsp::clear_birthdate() {
  birthdate_.ClearToEmpty();
}
inline const std::string& AppBusiBirthdateConvertRsp::birthdate() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
  return _internal_birthdate();
}
inline void AppBusiBirthdateConvertRsp::set_birthdate(const std::string& value) {
  _internal_set_birthdate(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
}
inline std::string* AppBusiBirthdateConvertRsp::mutable_birthdate() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
  return _internal_mutable_birthdate();
}
inline const std::string& AppBusiBirthdateConvertRsp::_internal_birthdate() const {
  return birthdate_.Get();
}
inline void AppBusiBirthdateConvertRsp::_internal_set_birthdate(const std::string& value) {
  
  birthdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppBusiBirthdateConvertRsp::set_birthdate(std::string&& value) {
  
  birthdate_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
}
inline void AppBusiBirthdateConvertRsp::set_birthdate(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  birthdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
}
inline void AppBusiBirthdateConvertRsp::set_birthdate(const char* value,
    size_t size) {
  
  birthdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
}
inline std::string* AppBusiBirthdateConvertRsp::_internal_mutable_birthdate() {
  
  return birthdate_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppBusiBirthdateConvertRsp::release_birthdate() {
  // @@protoc_insertion_point(field_release:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
  return birthdate_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppBusiBirthdateConvertRsp::set_allocated_birthdate(std::string* birthdate) {
  if (birthdate != nullptr) {
    
  } else {
    
  }
  birthdate_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), birthdate,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppBusiBirthdateConvertRsp.birthdate)
}

// string gz_year = 2;
inline void AppBusiBirthdateConvertRsp::clear_gz_year() {
  gz_year_.ClearToEmpty();
}
inline const std::string& AppBusiBirthdateConvertRsp::gz_year() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBirthdateConvertRsp.gz_year)
  return _internal_gz_year();
}
inline void AppBusiBirthdateConvertRsp::set_gz_year(const std::string& value) {
  _internal_set_gz_year(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBirthdateConvertRsp.gz_year)
}
inline std::string* AppBusiBirthdateConvertRsp::mutable_gz_year() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppBusiBirthdateConvertRsp.gz_year)
  return _internal_mutable_gz_year();
}
inline const std::string& AppBusiBirthdateConvertRsp::_internal_gz_year() const {
  return gz_year_.Get();
}
inline void AppBusiBirthdateConvertRsp::_internal_set_gz_year(const std::string& value) {
  
  gz_year_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppBusiBirthdateConvertRsp::set_gz_year(std::string&& value) {
  
  gz_year_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppBusiBirthdateConvertRsp.gz_year)
}
inline void AppBusiBirthdateConvertRsp::set_gz_year(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  gz_year_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppBusiBirthdateConvertRsp.gz_year)
}
inline void AppBusiBirthdateConvertRsp::set_gz_year(const char* value,
    size_t size) {
  
  gz_year_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppBusiBirthdateConvertRsp.gz_year)
}
inline std::string* AppBusiBirthdateConvertRsp::_internal_mutable_gz_year() {
  
  return gz_year_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppBusiBirthdateConvertRsp::release_gz_year() {
  // @@protoc_insertion_point(field_release:trpc.app.AppBusiBirthdateConvertRsp.gz_year)
  return gz_year_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppBusiBirthdateConvertRsp::set_allocated_gz_year(std::string* gz_year) {
  if (gz_year != nullptr) {
    
  } else {
    
  }
  gz_year_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), gz_year,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppBusiBirthdateConvertRsp.gz_year)
}

// string gz_month = 3;
inline void AppBusiBirthdateConvertRsp::clear_gz_month() {
  gz_month_.ClearToEmpty();
}
inline const std::string& AppBusiBirthdateConvertRsp::gz_month() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBirthdateConvertRsp.gz_month)
  return _internal_gz_month();
}
inline void AppBusiBirthdateConvertRsp::set_gz_month(const std::string& value) {
  _internal_set_gz_month(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBirthdateConvertRsp.gz_month)
}
inline std::string* AppBusiBirthdateConvertRsp::mutable_gz_month() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppBusiBirthdateConvertRsp.gz_month)
  return _internal_mutable_gz_month();
}
inline const std::string& AppBusiBirthdateConvertRsp::_internal_gz_month() const {
  return gz_month_.Get();
}
inline void AppBusiBirthdateConvertRsp::_internal_set_gz_month(const std::string& value) {
  
  gz_month_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppBusiBirthdateConvertRsp::set_gz_month(std::string&& value) {
  
  gz_month_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppBusiBirthdateConvertRsp.gz_month)
}
inline void AppBusiBirthdateConvertRsp::set_gz_month(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  gz_month_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppBusiBirthdateConvertRsp.gz_month)
}
inline void AppBusiBirthdateConvertRsp::set_gz_month(const char* value,
    size_t size) {
  
  gz_month_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppBusiBirthdateConvertRsp.gz_month)
}
inline std::string* AppBusiBirthdateConvertRsp::_internal_mutable_gz_month() {
  
  return gz_month_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppBusiBirthdateConvertRsp::release_gz_month() {
  // @@protoc_insertion_point(field_release:trpc.app.AppBusiBirthdateConvertRsp.gz_month)
  return gz_month_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppBusiBirthdateConvertRsp::set_allocated_gz_month(std::string* gz_month) {
  if (gz_month != nullptr) {
    
  } else {
    
  }
  gz_month_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), gz_month,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppBusiBirthdateConvertRsp.gz_month)
}

// string gz_day = 4;
inline void AppBusiBirthdateConvertRsp::clear_gz_day() {
  gz_day_.ClearToEmpty();
}
inline const std::string& AppBusiBirthdateConvertRsp::gz_day() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBirthdateConvertRsp.gz_day)
  return _internal_gz_day();
}
inline void AppBusiBirthdateConvertRsp::set_gz_day(const std::string& value) {
  _internal_set_gz_day(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBirthdateConvertRsp.gz_day)
}
inline std::string* AppBusiBirthdateConvertRsp::mutable_gz_day() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppBusiBirthdateConvertRsp.gz_day)
  return _internal_mutable_gz_day();
}
inline const std::string& AppBusiBirthdateConvertRsp::_internal_gz_day() const {
  return gz_day_.Get();
}
inline void AppBusiBirthdateConvertRsp::_internal_set_gz_day(const std::string& value) {
  
  gz_day_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppBusiBirthdateConvertRsp::set_gz_day(std::string&& value) {
  
  gz_day_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppBusiBirthdateConvertRsp.gz_day)
}
inline void AppBusiBirthdateConvertRsp::set_gz_day(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  gz_day_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppBusiBirthdateConvertRsp.gz_day)
}
inline void AppBusiBirthdateConvertRsp::set_gz_day(const char* value,
    size_t size) {
  
  gz_day_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppBusiBirthdateConvertRsp.gz_day)
}
inline std::string* AppBusiBirthdateConvertRsp::_internal_mutable_gz_day() {
  
  return gz_day_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppBusiBirthdateConvertRsp::release_gz_day() {
  // @@protoc_insertion_point(field_release:trpc.app.AppBusiBirthdateConvertRsp.gz_day)
  return gz_day_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppBusiBirthdateConvertRsp::set_allocated_gz_day(std::string* gz_day) {
  if (gz_day != nullptr) {
    
  } else {
    
  }
  gz_day_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), gz_day,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppBusiBirthdateConvertRsp.gz_day)
}

// string gz_hour = 5;
inline void AppBusiBirthdateConvertRsp::clear_gz_hour() {
  gz_hour_.ClearToEmpty();
}
inline const std::string& AppBusiBirthdateConvertRsp::gz_hour() const {
  // @@protoc_insertion_point(field_get:trpc.app.AppBusiBirthdateConvertRsp.gz_hour)
  return _internal_gz_hour();
}
inline void AppBusiBirthdateConvertRsp::set_gz_hour(const std::string& value) {
  _internal_set_gz_hour(value);
  // @@protoc_insertion_point(field_set:trpc.app.AppBusiBirthdateConvertRsp.gz_hour)
}
inline std::string* AppBusiBirthdateConvertRsp::mutable_gz_hour() {
  // @@protoc_insertion_point(field_mutable:trpc.app.AppBusiBirthdateConvertRsp.gz_hour)
  return _internal_mutable_gz_hour();
}
inline const std::string& AppBusiBirthdateConvertRsp::_internal_gz_hour() const {
  return gz_hour_.Get();
}
inline void AppBusiBirthdateConvertRsp::_internal_set_gz_hour(const std::string& value) {
  
  gz_hour_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AppBusiBirthdateConvertRsp::set_gz_hour(std::string&& value) {
  
  gz_hour_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:trpc.app.AppBusiBirthdateConvertRsp.gz_hour)
}
inline void AppBusiBirthdateConvertRsp::set_gz_hour(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  gz_hour_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:trpc.app.AppBusiBirthdateConvertRsp.gz_hour)
}
inline void AppBusiBirthdateConvertRsp::set_gz_hour(const char* value,
    size_t size) {
  
  gz_hour_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:trpc.app.AppBusiBirthdateConvertRsp.gz_hour)
}
inline std::string* AppBusiBirthdateConvertRsp::_internal_mutable_gz_hour() {
  
  return gz_hour_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AppBusiBirthdateConvertRsp::release_gz_hour() {
  // @@protoc_insertion_point(field_release:trpc.app.AppBusiBirthdateConvertRsp.gz_hour)
  return gz_hour_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AppBusiBirthdateConvertRsp::set_allocated_gz_hour(std::string* gz_hour) {
  if (gz_hour != nullptr) {
    
  } else {
    
  }
  gz_hour_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), gz_hour,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:trpc.app.AppBusiBirthdateConvertRsp.gz_hour)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace app
}  // namespace trpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_app_5fbusi_5fitg_5fserver_2eproto
