//
// This file was generated by trpc_cpp_plugin which is a self-defined pb compiler plugin, do not edit it!!!
// All rights reserved by Tencent Corporation
//

#pragma once

#include "trpc_sample_server.pb.h"

#include "trpc/client/rpc_service_proxy.h"
#include "trpc/server/rpc_service_impl.h"

namespace trpc {
namespace sample {

class TrpcSampleService : public ::trpc::RpcServiceImpl {
 public:
  TrpcSampleService();

  virtual ::trpc::Status TrpcSampleHandler(::trpc::ServerContextPtr context, const ::trpc::sample::TrpcSampleReq* request, ::trpc::sample::TrpcSampleRsp* response);
};

class AsyncTrpcSampleService : public ::trpc::AsyncRpcServiceImpl {
 public:
  AsyncTrpcSampleService();
  
  virtual ::trpc::Future<::trpc::sample::TrpcSampleRsp> TrpcSampleHandler(const ::trpc::ServerContextPtr& context, const ::trpc::sample::TrpcSampleReq* request);
};

class TrpcSampleServiceServiceProxy : public ::trpc::RpcServiceProxy {
 public:
  virtual ::trpc::Status TrpcSampleHandler(const ::trpc::ClientContextPtr& context, const ::trpc::sample::TrpcSampleReq& request, ::trpc::sample::TrpcSampleRsp* response);
  virtual ::trpc::Future<::trpc::sample::TrpcSampleRsp> AsyncTrpcSampleHandler(const ::trpc::ClientContextPtr& context, const ::trpc::sample::TrpcSampleReq& request);
  // oneway, only send
  virtual ::trpc::Status TrpcSampleHandler(const ::trpc::ClientContextPtr& context, const ::trpc::sample::TrpcSampleReq& request);
};

class AsyncTrpcSampleServiceServiceProxy : public ::trpc::RpcServiceProxy {
 public:
  ::trpc::Future<::trpc::sample::TrpcSampleRsp> TrpcSampleHandler(const ::trpc::ClientContextPtr& context, const ::trpc::sample::TrpcSampleReq& request);
  // TODO: one-way
};

} // end namespace sample
} // end namespace trpc