// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ggg_template_server.proto

#include "ggg_template_server.pb.h"
#include "ggg_template_server.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ggg_template_server {

static const char* GggTemplateServer_method_names[] = {
  "/ggg_template_server.GggTemplateServer/TemplateReqHandler",
};

std::unique_ptr< GggTemplateServer::Stub> GggTemplateServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GggTemplateServer::Stub> stub(new GggTemplateServer::Stub(channel, options));
  return stub;
}

GggTemplateServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_TemplateReqHandler_(GggTemplateServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GggTemplateServer::Stub::TemplateReqHandler(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq& request, ::ggg_template_server::TemplateRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ggg_template_server::TemplateReq, ::ggg_template_server::TemplateRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TemplateReqHandler_, context, request, response);
}

void GggTemplateServer::Stub::async::TemplateReqHandler(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq* request, ::ggg_template_server::TemplateRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ggg_template_server::TemplateReq, ::ggg_template_server::TemplateRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TemplateReqHandler_, context, request, response, std::move(f));
}

void GggTemplateServer::Stub::async::TemplateReqHandler(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq* request, ::ggg_template_server::TemplateRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TemplateReqHandler_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ggg_template_server::TemplateRsp>* GggTemplateServer::Stub::PrepareAsyncTemplateReqHandlerRaw(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ggg_template_server::TemplateRsp, ::ggg_template_server::TemplateReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TemplateReqHandler_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ggg_template_server::TemplateRsp>* GggTemplateServer::Stub::AsyncTemplateReqHandlerRaw(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTemplateReqHandlerRaw(context, request, cq);
  result->StartCall();
  return result;
}

GggTemplateServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GggTemplateServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GggTemplateServer::Service, ::ggg_template_server::TemplateReq, ::ggg_template_server::TemplateRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GggTemplateServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ggg_template_server::TemplateReq* req,
             ::ggg_template_server::TemplateRsp* resp) {
               return service->TemplateReqHandler(ctx, req, resp);
             }, this)));
}

GggTemplateServer::Service::~Service() {
}

::grpc::Status GggTemplateServer::Service::TemplateReqHandler(::grpc::ServerContext* context, const ::ggg_template_server::TemplateReq* request, ::ggg_template_server::TemplateRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ggg_template_server

