// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ggg_template_server.proto
// Original file comments:
// Copyright 2023 skylanwei authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_ggg_5ftemplate_5fserver_2eproto__INCLUDED
#define GRPC_ggg_5ftemplate_5fserver_2eproto__INCLUDED

#include "ggg_template_server.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ggg_template_server {

// The template server's service definition.
class GggTemplateServer final {
 public:
  static constexpr char const* service_full_name() {
    return "ggg_template_server.GggTemplateServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status TemplateReqHandler(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq& request, ::ggg_template_server::TemplateRsp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ggg_template_server::TemplateRsp>> AsyncTemplateReqHandler(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ggg_template_server::TemplateRsp>>(AsyncTemplateReqHandlerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ggg_template_server::TemplateRsp>> PrepareAsyncTemplateReqHandler(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ggg_template_server::TemplateRsp>>(PrepareAsyncTemplateReqHandlerRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void TemplateReqHandler(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq* request, ::ggg_template_server::TemplateRsp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void TemplateReqHandler(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq* request, ::ggg_template_server::TemplateRsp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ggg_template_server::TemplateRsp>* AsyncTemplateReqHandlerRaw(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ggg_template_server::TemplateRsp>* PrepareAsyncTemplateReqHandlerRaw(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status TemplateReqHandler(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq& request, ::ggg_template_server::TemplateRsp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ggg_template_server::TemplateRsp>> AsyncTemplateReqHandler(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ggg_template_server::TemplateRsp>>(AsyncTemplateReqHandlerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ggg_template_server::TemplateRsp>> PrepareAsyncTemplateReqHandler(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ggg_template_server::TemplateRsp>>(PrepareAsyncTemplateReqHandlerRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void TemplateReqHandler(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq* request, ::ggg_template_server::TemplateRsp* response, std::function<void(::grpc::Status)>) override;
      void TemplateReqHandler(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq* request, ::ggg_template_server::TemplateRsp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ggg_template_server::TemplateRsp>* AsyncTemplateReqHandlerRaw(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ggg_template_server::TemplateRsp>* PrepareAsyncTemplateReqHandlerRaw(::grpc::ClientContext* context, const ::ggg_template_server::TemplateReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_TemplateReqHandler_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status TemplateReqHandler(::grpc::ServerContext* context, const ::ggg_template_server::TemplateReq* request, ::ggg_template_server::TemplateRsp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_TemplateReqHandler : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TemplateReqHandler() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_TemplateReqHandler() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TemplateReqHandler(::grpc::ServerContext* /*context*/, const ::ggg_template_server::TemplateReq* /*request*/, ::ggg_template_server::TemplateRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTemplateReqHandler(::grpc::ServerContext* context, ::ggg_template_server::TemplateReq* request, ::grpc::ServerAsyncResponseWriter< ::ggg_template_server::TemplateRsp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_TemplateReqHandler<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_TemplateReqHandler : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_TemplateReqHandler() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ggg_template_server::TemplateReq, ::ggg_template_server::TemplateRsp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ggg_template_server::TemplateReq* request, ::ggg_template_server::TemplateRsp* response) { return this->TemplateReqHandler(context, request, response); }));}
    void SetMessageAllocatorFor_TemplateReqHandler(
        ::grpc::MessageAllocator< ::ggg_template_server::TemplateReq, ::ggg_template_server::TemplateRsp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ggg_template_server::TemplateReq, ::ggg_template_server::TemplateRsp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_TemplateReqHandler() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TemplateReqHandler(::grpc::ServerContext* /*context*/, const ::ggg_template_server::TemplateReq* /*request*/, ::ggg_template_server::TemplateRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TemplateReqHandler(
      ::grpc::CallbackServerContext* /*context*/, const ::ggg_template_server::TemplateReq* /*request*/, ::ggg_template_server::TemplateRsp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_TemplateReqHandler<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_TemplateReqHandler : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TemplateReqHandler() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_TemplateReqHandler() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TemplateReqHandler(::grpc::ServerContext* /*context*/, const ::ggg_template_server::TemplateReq* /*request*/, ::ggg_template_server::TemplateRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_TemplateReqHandler : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TemplateReqHandler() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_TemplateReqHandler() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TemplateReqHandler(::grpc::ServerContext* /*context*/, const ::ggg_template_server::TemplateReq* /*request*/, ::ggg_template_server::TemplateRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTemplateReqHandler(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_TemplateReqHandler : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_TemplateReqHandler() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->TemplateReqHandler(context, request, response); }));
    }
    ~WithRawCallbackMethod_TemplateReqHandler() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TemplateReqHandler(::grpc::ServerContext* /*context*/, const ::ggg_template_server::TemplateReq* /*request*/, ::ggg_template_server::TemplateRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TemplateReqHandler(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TemplateReqHandler : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_TemplateReqHandler() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ggg_template_server::TemplateReq, ::ggg_template_server::TemplateRsp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ggg_template_server::TemplateReq, ::ggg_template_server::TemplateRsp>* streamer) {
                       return this->StreamedTemplateReqHandler(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_TemplateReqHandler() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TemplateReqHandler(::grpc::ServerContext* /*context*/, const ::ggg_template_server::TemplateReq* /*request*/, ::ggg_template_server::TemplateRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTemplateReqHandler(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ggg_template_server::TemplateReq,::ggg_template_server::TemplateRsp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_TemplateReqHandler<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_TemplateReqHandler<Service > StreamedService;
};

}  // namespace ggg_template_server


#endif  // GRPC_ggg_5ftemplate_5fserver_2eproto__INCLUDED
